import type { Pool, PoolClient } from 'pg';
import type { LearningStoreContract } from '../store-contract.js';
import type { EvidenceInput, InterventionRecord, MisconceptionRecord, MisconceptionState, ResumeState, ReviewRecord } from '../store-types.js';
const iso=(value:unknown)=>new Date(String(value)).toISOString();type Row=Record<string,unknown>;
export class PostgresLearningStore implements LearningStoreContract{
 constructor(private readonly pool:Pool){} async close(){await this.pool.end();}
 async query(sql:string,params:unknown[]=[]){const r=await this.pool.query(sql,params);return{rows:r.rows as Row[]};}
 private async one(sql:string,params:unknown[]=[]){const r=await this.pool.query(sql,params);return r.rows[0] as Row|undefined;} private async many(sql:string,params:unknown[]=[]){const r=await this.pool.query(sql,params);return r.rows as Row[];}
 private misconception(r:Row):MisconceptionRecord{return{id:Number(r.id),studentId:Number(r.student_id),conceptId:String(r.concept_id),code:String(r.code),severity:Number(r.severity),status:r.status as MisconceptionRecord['status'],occurrences:Number(r.occurrences),lastEvidenceId:r.last_evidence_id==null?null:Number(r.last_evidence_id),updatedAt:iso(r.updated_at)};}
 private intervention(r:Row):InterventionRecord{return{id:Number(r.id),studentId:Number(r.student_id),misconceptionId:Number(r.misconception_id),conceptId:String(r.concept_id),prerequisiteConceptId:String(r.prerequisite_concept_id),problemId:String(r.problem_id),stage:r.stage as InterventionRecord['stage'],strategy:String(r.strategy),status:r.status as InterventionRecord['status'],createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}
 async getSession(id:number){const r=await this.one('SELECT status,current_concept,diagnostic_index,updated_at FROM learner_sessions WHERE student_id=$1',[id]);return r?{status:String(r.status),currentConcept:r.current_concept==null?null:String(r.current_concept),diagnosticIndex:Number(r.diagnostic_index),updatedAt:iso(r.updated_at)}:undefined;}
 async saveSession(id:number,status:string,concept:string|null,index=0){await this.pool.query(`INSERT INTO learner_sessions(student_id,status,current_concept,diagnostic_index) VALUES($1,$2,$3,$4) ON CONFLICT(student_id) DO UPDATE SET status=EXCLUDED.status,current_concept=EXCLUDED.current_concept,diagnostic_index=EXCLUDED.diagnostic_index,updated_at=now()`,[id,status,concept,index]);}
 async ensureStudent(nickname:string){const r=await this.one('INSERT INTO students(nickname) VALUES($1) ON CONFLICT(nickname) DO UPDATE SET nickname=EXCLUDED.nickname RETURNING id',[nickname]);return Number(r!.id);}
 async getMastery(id:number){const rows=await this.many('SELECT concept_id,score FROM mastery WHERE student_id=$1',[id]);return Object.fromEntries(rows.map(r=>[String(r.concept_id),Number(r.score)]));}
 async setMastery(id:number,concept:string,score:number){await this.pool.query(`INSERT INTO mastery(student_id,concept_id,score) VALUES($1,$2,$3) ON CONFLICT(student_id,concept_id) DO UPDATE SET score=EXCLUDED.score,updated_at=now()`,[id,concept,Math.max(0,Math.min(100,score))]);}
 async recordMastery(id:number,concept:string,correct:boolean){const c=correct?1:0;await this.pool.query(`INSERT INTO mastery(student_id,concept_id,score,attempts,correct) VALUES($1,$2,$3,1,$4) ON CONFLICT(student_id,concept_id) DO UPDATE SET attempts=mastery.attempts+1,correct=mastery.correct+$4,score=(mastery.correct+$4)::double precision/(mastery.attempts+1)*100,updated_at=now()`,[id,concept,c?100:0,c]);}
 async addEvidence(id:number,concept:string,x:EvidenceInput){const r=await this.one(`INSERT INTO evidence(student_id,concept_id,kind,value,note,lesson_id,problem_id,reasoning,confidence,hint_used,duration_seconds) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[id,concept,x.kind,x.value??null,x.note??null,x.lessonId??null,x.problemId??null,x.reasoning??null,x.confidence??null,x.hintUsed??false,x.durationSeconds??null]);return Number(r!.id);}
 async recordAttemptEvidenceAndMastery(id:number,concept:string,x:EvidenceInput,correct:boolean){return this.transaction(async(client)=>{const evidence=await client.query(`INSERT INTO evidence(student_id,concept_id,kind,value,note,lesson_id,problem_id,reasoning,confidence,hint_used,duration_seconds) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[id,concept,x.kind,x.value??null,x.note??null,x.lessonId??null,x.problemId??null,x.reasoning??null,x.confidence??null,x.hintUsed??false,x.durationSeconds??null]);const c=correct?1:0;await client.query(`INSERT INTO mastery(student_id,concept_id,score,attempts,correct) VALUES($1,$2,$3,1,$4) ON CONFLICT(student_id,concept_id) DO UPDATE SET attempts=mastery.attempts+1,correct=mastery.correct+$4,score=(mastery.correct+$4)::double precision/(mastery.attempts+1)*100,updated_at=now()`,[id,concept,c?100:0,c]);return Number(evidence.rows[0].id);});}
 async upsertMisconception(id:number,concept:string,code:string,severity:number,evidence:number){const r=await this.one(`INSERT INTO misconceptions(student_id,concept_id,code,severity,last_evidence_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(student_id,concept_id,code) DO UPDATE SET severity=GREATEST(misconceptions.severity,EXCLUDED.severity),occurrences=misconceptions.occurrences+1,last_evidence_id=EXCLUDED.last_evidence_id,status='active',updated_at=now() RETURNING *`,[id,concept,code,severity,evidence]);await this.pool.query('INSERT INTO misconception_state(misconception_id) VALUES($1) ON CONFLICT DO NOTHING',[r!.id]);return this.misconception(r!);}
 async listMisconceptions(id:number,concept?:string){const rows=await this.many(concept?'SELECT * FROM misconceptions WHERE student_id=$1 AND concept_id=$2 ORDER BY severity DESC,updated_at DESC':'SELECT * FROM misconceptions WHERE student_id=$1 ORDER BY severity DESC,updated_at DESC',concept?[id,concept]:[id]);return rows.map(r=>this.misconception(r));}
 async getMisconceptionState(id:number){const r=await this.one('SELECT * FROM misconception_state WHERE misconception_id=$1',[id]);return r?{misconceptionId:Number(r.misconception_id),confidence:Number(r.confidence),positiveEvidence:Number(r.positive_evidence),negativeEvidence:Number(r.negative_evidence),lastVerdict:r.last_verdict==null?null:String(r.last_verdict),updatedAt:iso(r.updated_at)}:undefined;}
 async recordMisconceptionSignal(id:number,verdict:string){const neg=verdict==='still_present'||verdict==='new_misconception',delta=neg?15:verdict==='repaired'?-30:0;const r=await this.one(`INSERT INTO misconception_state(misconception_id,confidence,positive_evidence,negative_evidence,last_verdict) VALUES($1,$2,$3,$4,$5) ON CONFLICT(misconception_id) DO UPDATE SET confidence=GREATEST(0,LEAST(100,misconception_state.confidence+$6)),positive_evidence=misconception_state.positive_evidence+$7,negative_evidence=misconception_state.negative_evidence+$8,last_verdict=EXCLUDED.last_verdict,updated_at=now() RETURNING *`,[id,Math.max(0,delta),verdict==='repaired'?1:0,neg?1:0,verdict,delta,verdict==='repaired'?1:0,neg?1:0]);if(neg)await this.pool.query("UPDATE misconceptions SET status='active',updated_at=now() WHERE id=$1",[id]);return{misconceptionId:Number(r!.misconception_id),confidence:Number(r!.confidence),positiveEvidence:Number(r!.positive_evidence),negativeEvidence:Number(r!.negative_evidence),lastVerdict:String(r!.last_verdict),updatedAt:iso(r!.updated_at)};}
 async markMisconceptionRepaired(student:number,id:number){const s=await this.getMisconceptionState(id);if(!s||s.positiveEvidence<2||s.confidence>30)throw new Error('Misconception cannot be resolved without repeated positive repair evidence');const r=await this.pool.query("UPDATE misconceptions SET status='resolved',updated_at=now() WHERE id=$1 AND student_id=$2",[id,student]);if(r.rowCount!==1)throw new Error('Misconception does not belong to learner');}
 async getIntervention(id:number){const r=await this.one('SELECT * FROM interventions WHERE id=$1',[id]);return r?this.intervention(r):undefined;}
 async listInterventions(id:number,status?:string){const rows=await this.many(status?'SELECT * FROM interventions WHERE student_id=$1 AND status=$2 ORDER BY id':`SELECT * FROM interventions WHERE student_id=$1 ORDER BY CASE status WHEN 'active' THEN 0 WHEN 'queued' THEN 1 ELSE 2 END,id`,status?[id,status]:[id]);return rows.map(r=>this.intervention(r));}
 async queueIntervention(student:number,m:number,concept:string,pre:string,problem:string,stage:'discrimination'|'transfer',strategy:string){const old=await this.one("SELECT * FROM interventions WHERE student_id=$1 AND misconception_id=$2 AND stage=$3 AND status IN ('queued','active') ORDER BY id LIMIT 1",[student,m,stage]);if(old)return this.intervention(old);const r=await this.one('INSERT INTO interventions(student_id,misconception_id,concept_id,prerequisite_concept_id,problem_id,stage,strategy) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[student,m,concept,pre,problem,stage,strategy]);return this.intervention(r!);}
 async activateIntervention(id:number){await this.pool.query("UPDATE interventions SET status='active',updated_at=now() WHERE id=$1 AND status='queued'",[id]);} async completeIntervention(id:number){await this.pool.query("UPDATE interventions SET status='completed',updated_at=now() WHERE id=$1",[id]);}
 async addRemediationAttempt(i:number,e:number,v:string,s:number){const r=await this.one('INSERT INTO remediation_attempts(intervention_id,evidence_id,verdict,checkpoint_score) VALUES($1,$2,$3,$4) RETURNING id',[i,e,v,s]);return Number(r!.id);}
 async scheduleReview(student:number,concept:string,score:number,at=new Date()){const old=await this.one('SELECT interval_days,streak FROM concept_reviews WHERE student_id=$1 AND concept_id=$2',[student,concept]);const strong=score>=.8,streak=strong?Number(old?.streak??0)+1:0,prev=Number(old?.interval_days??0),days=strong?Math.min(90,prev===0?1:prev*(streak>=3?3:2)):1,due=new Date(at.getTime()+days*86400000);const r=await this.one(`INSERT INTO concept_reviews(student_id,concept_id,due_at,interval_days,streak,last_score,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(student_id,concept_id) DO UPDATE SET due_at=EXCLUDED.due_at,interval_days=EXCLUDED.interval_days,streak=EXCLUDED.streak,last_score=EXCLUDED.last_score,updated_at=EXCLUDED.updated_at RETURNING *`,[student,concept,due.toISOString(),days,streak,score,at.toISOString()]);return{studentId:student,conceptId:concept,dueAt:iso(r!.due_at),intervalDays:Number(r!.interval_days),streak:Number(r!.streak),lastScore:Number(r!.last_score),updatedAt:iso(r!.updated_at)};}
 async listDueReviews(id:number,when=new Date().toISOString()){const rows=await this.many('SELECT * FROM concept_reviews WHERE student_id=$1 AND due_at<=$2 ORDER BY due_at',[id,when]);return rows.map(r=>({studentId:Number(r.student_id),conceptId:String(r.concept_id),dueAt:iso(r.due_at),intervalDays:Number(r.interval_days),streak:Number(r.streak),lastScore:Number(r.last_score),updatedAt:iso(r.updated_at)}));}
 async addReviewAttempt(s:number,c:string,p:string,e:number,o:string,score:number){const r=await this.one('INSERT INTO review_attempts(student_id,concept_id,problem_id,evidence_id,outcome,checkpoint_score) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[s,c,p,e,o,score]);return Number(r!.id);}
 async resolveMisconception(s:number,id:number){await this.markMisconceptionRepaired(s,id);}
 async saveResume(s:number,l:string|null,p:string|null,step:number,state:unknown=null){if(!Number.isInteger(step)||step<0)throw new Error('Resume step must be a non-negative integer');await this.pool.query(`INSERT INTO resume_state(student_id,lesson_id,problem_id,step,state_json) VALUES($1,$2,$3,$4,$5) ON CONFLICT(student_id) DO UPDATE SET lesson_id=EXCLUDED.lesson_id,problem_id=EXCLUDED.problem_id,step=EXCLUDED.step,state_json=EXCLUDED.state_json,updated_at=now()`,[s,l,p,step,state===null?null:JSON.stringify(state)]);}
 async getResume(s:number){const r=await this.one('SELECT * FROM resume_state WHERE student_id=$1',[s]);return r?{lessonId:r.lesson_id==null?null:String(r.lesson_id),problemId:r.problem_id==null?null:String(r.problem_id),step:Number(r.step),stateJson:r.state_json==null?null:JSON.stringify(r.state_json),updatedAt:iso(r.updated_at)}:undefined;}
 async transaction<T>(work:(client:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query('BEGIN');const out=await work(c);await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
}
