import type { Pool, PoolClient } from 'pg';
import type { LearningStoreContract } from '../store-contract.js';
import type { EvidenceInput, InterventionRecord, MisconceptionRecord, MisconceptionState, ResumeState, ReviewRecord } from '../store-types.js';

const iso = (value: unknown) => new Date(String(value)).toISOString();
type Row = Record<string, unknown>;

export class PostgresLearningStore implements LearningStoreContract {
  constructor(private readonly pool: Pool) {}
  async close(): Promise<void> { await this.pool.end(); }
  private async one(sql:string, params:unknown[]=[]):Promise<Row|undefined>{ const r=await this.pool.query(sql,params); return r.rows[0] as Row|undefined; }
  private async many(sql:string, params:unknown[]=[]):Promise<Row[]>{ const r=await this.pool.query(sql,params); return r.rows as Row[]; }
  private misconception(r:Row):MisconceptionRecord{return{id:Number(r.id),studentId:Number(r.student_id),conceptId:String(r.concept_id),code:String(r.code),severity:Number(r.severity),status:r.status as MisconceptionRecord['status'],occurrences:Number(r.occurrences),lastEvidenceId:r.last_evidence_id==null?null:Number(r.last_evidence_id),updatedAt:iso(r.updated_at)};}
  private intervention(r:Row):InterventionRecord{return{id:Number(r.id),studentId:Number(r.student_id),misconceptionId:Number(r.misconception_id),conceptId:String(r.concept_id),prerequisiteConceptId:String(r.prerequisite_concept_id),problemId:String(r.problem_id),stage:r.stage as InterventionRecord['stage'],strategy:String(r.strategy),status:r.status as InterventionRecord['status'],createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}
  async getSession(studentId:number){const r=await this.one('SELECT status,current_concept,diagnostic_index,updated_at FROM learner_sessions WHERE student_id=$1',[studentId]);return r?{status:String(r.status),currentConcept:r.current_concept==null?null:String(r.current_concept),diagnosticIndex:Number(r.diagnostic_index),updatedAt:iso(r.updated_at)}:undefined;}
  async saveSession(studentId:number,status:string,currentConcept:string|null,diagnosticIndex=0){await this.pool.query(`INSERT INTO learner_sessions(student_id,status,current_concept,diagnostic_index) VALUES($1,$2,$3,$4) ON CONFLICT(student_id) DO UPDATE SET status=EXCLUDED.status,current_concept=EXCLUDED.current_concept,diagnostic_index=EXCLUDED.diagnostic_index,updated_at=now()`,[studentId,status,currentConcept,diagnosticIndex]);}
  async ensureStudent(nickname:string){const r=await this.one(`INSERT INTO students(nickname) VALUES($1) ON CONFLICT(nickname) DO UPDATE SET nickname=EXCLUDED.nickname RETURNING id`,[nickname]);return Number(r!.id);}
  async getMastery(studentId:number){const rows=await this.many('SELECT concept_id,score FROM mastery WHERE student_id=$1',[studentId]);return Object.fromEntries(rows.map(r=>[String(r.concept_id),Number(r.score)]));}
  async setMastery(studentId:number,conceptId:string,score:number){const s=Math.max(0,Math.min(100,score));await this.pool.query(`INSERT INTO mastery(student_id,concept_id,score) VALUES($1,$2,$3) ON CONFLICT(student_id,concept_id) DO UPDATE SET score=EXCLUDED.score,updated_at=now()`,[studentId,conceptId,s]);}
  async recordMastery(studentId:number,conceptId:string,correct:boolean){await this.pool.query(`INSERT INTO mastery(student_id,concept_id,score,attempts,correct) VALUES($1,$2,$3,1,$4) ON CONFLICT(student_id,concept_id) DO UPDATE SET attempts=mastery.attempts+1,correct=mastery.correct+$4,score=(mastery.correct+$4)::double precision/(mastery.attempts+1)*100,updated_at=now()`,[studentId,conceptId,correct?100:0,correct?1:0]);}
  async addEvidence(studentId:number,conceptId:string,input:EvidenceInput){const r=await this.one(`INSERT INTO evidence(student_id,concept_id,kind,value,note,lesson_id,problem_id,reasoning,confidence,hint_used,duration_seconds) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[studentId,conceptId,input.kind,input.value??null,input.note??null,input.lessonId??null,input.problemId??null,input.reasoning??null,input.confidence??null,input.hintUsed??false,input.durationSeconds??null]);return Number(r!.id);}
  async upsertMisconception(studentId:number,conceptId:string,code:string,severity:number,evidenceId:number){const r=await this.one(`INSERT INTO misconceptions(student_id,concept_id,code,severity,last_evidence_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(student_id,concept_id,code) DO UPDATE SET severity=GREATEST(misconceptions.severity,EXCLUDED.severity),occurrences=misconceptions.occurrences+1,last_evidence_id=EXCLUDED.last_evidence_id,status='active',updated_at=now() RETURNING *`,[studentId,conceptId,code,severity,evidenceId]);await this.pool.query(`INSERT INTO misconception_state(misconception_id) VALUES($1) ON CONFLICT DO NOTHING`,[r!.id]);return this.misconception(r!);}
  async listMisconceptions(studentId:number,conceptId?:string){const rows=await this.many(conceptId?'SELECT * FROM misconceptions WHERE student_id=$1 AND concept_id=$2 ORDER BY severity DESC,updated_at DESC':'SELECT * FROM misconceptions WHERE student_id=$1 ORDER BY severity DESC,updated_at DESC',conceptId?[studentId,conceptId]:[studentId]);return rows.map(r=>this.misconception(r));}
  async getMisconceptionState(id:number){const r=await this.one('SELECT * FROM misconception_state WHERE misconception_id=$1',[id]);return r?{misconceptionId:Number(r.misconception_id),confidence:Number(r.confidence),positiveEvidence:Number(r.positive_evidence),negativeEvidence:Number(r.negative_evidence),lastVerdict:r.last_verdict==null?null:String(r.last_verdict),updatedAt:iso(r.updated_at)}:undefined;}
  async recordMisconceptionSignal(id:number,verdict:string){const negative=verdict==='still_present'||verdict==='new_misconception';const delta=negative?15:verdict==='repaired'?-30:0;const r=await this.one(`INSERT INTO misconception_state(misconception_id,confidence,positive_evidence,negative_evidence,last_verdict) VALUES($1,$2,$3,$4,$5) ON CONFLICT(misconception_id) DO UPDATE SET confidence=GREATEST(0,LEAST(100,misconception_state.confidence+$6)),positive_evidence=misconception_state.positive_evidence+$7,negative_evidence=misconception_state.negative_evidence+$8,last_verdict=EXCLUDED.last_verdict,updated_at=now() RETURNING *`,[id,Math.max(0,delta),verdict==='repaired'?1:0,negative?1:0,verdict,delta,verdict==='repaired'?1:0,negative?1:0]);if(negative)await this.pool.query("UPDATE misconceptions SET status='active',updated_at=now() WHERE id=$1",[id]);return{misconceptionId:Number(r!.misconception_id),confidence:Number(r!.confidence),positiveEvidence:Number(r!.positive_evidence),negativeEvidence:Number(r!.negative_evidence),lastVerdict:String(r!.last_verdict),updatedAt:iso(r!.updated_at)};}
  async markMisconceptionRepaired(studentId:number,id:number){const s=await this.getMisconceptionState(id);if(!s||s.positiveEvidence<2||s.confidence>30)throw new Error('Misconception cannot be resolved without repeated positive repair evidence');const r=await this.pool.query("UPDATE misconceptions SET status='resolved',updated_at=now() WHERE id=$1 AND student_id=$2",[id,studentId]);if(r.rowCount!==1)throw new Error('Misconception does not belong to learner');}
  async getIntervention(id:number){const r=await this.one('SELECT * FROM interventions WHERE id=$1',[id]);return r?this.intervention(r):undefined;}
  async listInterventions(studentId:number,status?:string){const rows=await this.many(status?'SELECT * FROM interventions WHERE student_id=$1 AND status=$2 ORDER BY id':'SELECT * FROM interventions WHERE student_id=$1 ORDER BY CASE status WHEN \'active\' THEN 0 WHEN \'queued\' THEN 1 ELSE 2 END,id',status?[studentId,status]:[studentId]);return rows.map(r=>this.intervention(r));}
  async queueIntervention(studentId:number,misconceptionId:number,conceptId:string,prerequisiteConceptId:string,problemId:string,stage:'discrimination'|'transfer',strategy:string){const existing=await this.one("SELECT * FROM interventions WHERE student_id=$1 AND misconception_id=$2 AND stage=$3 AND status IN ('queued','active') ORDER BY id LIMIT 1",[studentId,misconceptionId,stage]);if(existing)return this.intervention(existing);const r=await this.one(`INSERT INTO interventions(student_id,misconception_id,concept_id,prerequisite_concept_id,problem_id,stage,strategy) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[studentId,misconceptionId,conceptId,prerequisiteConceptId,problemId,stage,strategy]);return this.intervention(r!);}
  async activateIntervention(id:number){await this.pool.query("UPDATE interventions SET status='active',updated_at=now() WHERE id=$1 AND status='queued'",[id]);}
  async completeIntervention(id:number){await this.pool.query("UPDATE interventions SET status='completed',updated_at=now() WHERE id=$1",[id]);}
  async addRemediationAttempt(interventionId:number,evidenceId:number,verdict:string,checkpointScore:number){const r=await this.one('INSERT INTO remediation_attempts(intervention_id,evidence_id,verdict,checkpoint_score) VALUES($1,$2,$3,$4) RETURNING id',[interventionId,evidenceId,verdict,checkpointScore]);return Number(r!.id);}
  async scheduleReview(studentId:number,conceptId:string,score:number,referenceTime=new Date()){const old=await this.one('SELECT interval_days,streak FROM concept_reviews WHERE student_id=$1 AND concept_id=$2',[studentId,conceptId]);const strong=score>=0.8;const streak=strong?Number(old?.streak??0)+1:0;const previous=Number(old?.interval_days??0);const intervalDays=strong?Math.min(90,previous===0?1:previous*(streak>=3?3:2)):1;const due=new Date(referenceTime.getTime()+intervalDays*86400000);const r=await this.one(`INSERT INTO concept_reviews(student_id,concept_id,due_at,interval_days,streak,last_score,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(student_id,concept_id) DO UPDATE SET due_at=EXCLUDED.due_at,interval_days=EXCLUDED.interval_days,streak=EXCLUDED.streak,last_score=EXCLUDED.last_score,updated_at=EXCLUDED.updated_at RETURNING *`,[studentId,conceptId,due.toISOString(),intervalDays,streak,score,referenceTime.toISOString()]);return{studentId,conceptId,dueAt:iso(r!.due_at),intervalDays:Number(r!.interval_days),streak:Number(r!.streak),lastScore:Number(r!.last_score),updatedAt:iso(r!.updated_at)};}
  async listDueReviews(studentId:number,when=new Date().toISOString()){const rows=await this.many('SELECT * FROM concept_reviews WHERE student_id=$1 AND due_at<=$2 ORDER BY due_at',[studentId,when]);return rows.map(r=>({studentId:Number(r.student_id),conceptId:String(r.concept_id),dueAt:iso(r.due_at),intervalDays:Number(r.interval_days),streak:Number(r.streak),lastScore:Number(r.last_score),updatedAt:iso(r.updated_at)}));}
  async addReviewAttempt(studentId:number,conceptId:string,problemId:string,evidenceId:number,outcome:string,checkpointScore:number){const r=await this.one('INSERT INTO review_attempts(student_id,concept_id,problem_id,evidence_id,outcome,checkpoint_score) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[studentId,conceptId,problemId,evidenceId,outcome,checkpointScore]);return Number(r!.id);}
  async resolveMisconception(studentId:number,id:number){await this.markMisconceptionRepaired(studentId,id);}
  async saveResume(studentId:number,lessonId:string|null,problemId:string|null,step:number,state:unknown=null){if(!Number.isInteger(step)||step<0)throw new Error('Resume step must be a non-negative integer');await this.pool.query(`INSERT INTO resume_state(student_id,lesson_id,problem_id,step,state_json) VALUES($1,$2,$3,$4,$5) ON CONFLICT(student_id) DO UPDATE SET lesson_id=EXCLUDED.lesson_id,problem_id=EXCLUDED.problem_id,step=EXCLUDED.step,state_json=EXCLUDED.state_json,updated_at=now()`,[studentId,lessonId,problemId,step,state===null?null:JSON.stringify(state)]);}
  async getResume(studentId:number){const r=await this.one('SELECT * FROM resume_state WHERE student_id=$1',[studentId]);return r?{lessonId:r.lesson_id==null?null:String(r.lesson_id),problemId:r.problem_id==null?null:String(r.problem_id),step:Number(r.step),stateJson:r.state_json==null?null:JSON.stringify(r.state_json),updatedAt:iso(r.updated_at)}:undefined;}
  async transaction<T>(work:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query('BEGIN');const result=await work(client);await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
}
