import test from 'node:test';
import assert from 'node:assert/strict';
import { LearningStore } from '../src/store.js';
import { LearningEngine } from '../src/learning-engine.js';

test('real SQLite learner state survives a new engine instance', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const first=new LearningEngine(db);first.start(student);first.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100,graphs:100});first.recordAttempt(student,'motion',true,'correct velocity reasoning');const snapshot=new LearningEngine(db).snapshot(student);assert.equal(snapshot.mastery.motion,100);assert.equal(snapshot.status,'learning');db.close(); });
test('recording mastery changes the durable learner model', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Test');const engine=new LearningEngine(db);engine.start(student);const result=engine.recordAttempt(student,'arithmetic',true);assert.equal(result.mastery.arithmetic,100);db.close(); });
test('current concept cannot bypass requirements', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Test');const engine=new LearningEngine(db);engine.start(student);assert.throws(()=>engine.setCurrent(student,'forces'),/requirements/);db.close(); });
test('misconceptions resolve only through a successful remediation retry', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);engine.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100,algebra:100,graphs:100});const m=engine.recordMisconception(student,'motion','velocity-vs-speed','Treats velocity as scalar speed');const plan=engine.remediation(student,'motion');assert.deepEqual(plan,{misconceptionId:m.id,sourceConcept:'motion',targetConcept:'graphs',retryProblemId:'graphs-slope-speed',reason:'misconception',retryRequired:true});engine.retryRemediation(student,m.id,{problemId:'graphs-slope-speed',answer:'4',reasoning:'The slope is rise over run, but I am still unsure what it means.',confidence:70});assert.equal(engine.listOpenMisconceptions(student).length,1);engine.retryRemediation(student,m.id,{problemId:'graphs-slope-speed',answer:'5',reasoning:'The slope is change in position divided by time: 20 m / 4 s = 5 m/s, which represents speed.',confidence:90});assert.equal(engine.listOpenMisconceptions(student).length,0);assert.throws(()=>engine.resolveMisconception(m.id),/only be resolved/);db.close(); });
test('exact lesson resume state survives a new engine instance', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);engine.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100,graphs:100});engine.saveResume(student,'motion-from-change','motion-average-speed',4);const resumed=new LearningEngine(db).snapshot(student);assert.deepEqual(resumed.resume&&{lessonId:resumed.resume.lessonId,problemId:resumed.resume.problemId,step:resumed.resume.step},{lessonId:'motion-from-change',problemId:'motion-average-speed',step:4});db.close(); });
test('successful attempts schedule progressively spaced reviews', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);engine.recordAttempt(student,'arithmetic',true);engine.recordAttempt(student,'arithmetic',true);const reviews=db.db.prepare('SELECT interval_days,repetitions FROM reviews WHERE student_id=? AND concept_id=?').get(student,'arithmetic') as {interval_days:number;repetitions:number};assert.equal(reviews.interval_days,2);assert.equal(reviews.repetitions,2);db.close(); });
test('journey is derived from the same graph and learner state', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);assert.equal(engine.journey(student).find(n=>n.id==='measurement')?.status,'locked');db.setMastery(student,'arithmetic',100);db.setMastery(student,'measurement',100);assert.equal(engine.journey(student).find(n=>n.id==='measurement')?.status,'mastered');assert.equal(engine.journey(student).find(n=>n.id==='motion')?.status,'locked');db.close(); });
test('diagnostic evidence is weighted and persisted', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);const result=engine.diagnostic(student,[{conceptId:'measurement',score:60,kind:'diagnostic',difficulty:1},{conceptId:'measurement',score:100,kind:'transfer',difficulty:1}]);assert.equal(result.scores.measurement,83);assert.equal(result.confidence.measurement,0.78);assert.equal(db.getMastery(student).measurement,83);db.close(); });
test('diagnostic rejects impossible evidence', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);assert.throws(()=>engine.diagnostic(student,[{conceptId:'measurement',score:101,kind:'diagnostic',difficulty:1}]),/between 0 and 100/);db.close(); });
test('structured physics problems persist diagnostic reasoning', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);engine.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100,graphs:100});const problems=engine.problems(student,'motion');assert.ok(problems.length>=2);assert.ok(problems.every(p=>p.reasoningPrompts.length>0));const attempt=engine.submitProblem(student,{problemId:'motion-average-speed',answer:'5',reasoning:'Average speed is distance divided by elapsed time: 150/30 = 5 m/s.',confidence:80});assert.equal(attempt.correct,true);assert.equal(attempt.reasoningSignals.find(s=>s.id==='speed-model')?.present,true);assert.equal(attempt.reasoningSignals.find(s=>s.id==='units')?.present,true);assert.deepEqual(attempt.misconceptionCodes,[]);assert.equal(db.listProblemAttempts(student,'motion-average-speed').length,1);db.close(); });
test('incomplete reasoning creates durable misconception codes', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);engine.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100,graphs:100});const attempt=engine.submitProblem(student,{problemId:'motion-average-speed',answer:'150',reasoning:'I used the distance.',confidence:90});assert.equal(attempt.correct,false);assert.equal(attempt.reasoningSignals.find(s=>s.id==='speed-model')?.present,false);assert.ok(attempt.misconceptionCodes.includes('speed-wrong-model'));assert.ok(engine.listOpenMisconceptions(student,'motion').some(m=>m.code==='speed-wrong-model'));db.close(); });
test('reasoning coverage remains diagnostic even when answer is correct', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);engine.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100,graphs:100});const attempt=engine.submitProblem(student,{problemId:'motion-average-speed',answer:'5',reasoning:'150 divided by 30 gives 5.',confidence:60});assert.equal(attempt.correct,true);assert.ok(attempt.misconceptionCodes.includes('speed-missing-quantities'));assert.ok(attempt.misconceptionCodes.includes('speed-wrong-unit'));db.close(); });
test('problem submission requires reasoning and validates confidence', () => { const db=new LearningStore(':memory:');const student=db.ensureStudent('Ada');const engine=new LearningEngine(db);engine.start(student);engine.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100,graphs:100});assert.throws(()=>engine.submitProblem(student,{problemId:'motion-average-speed',answer:'5',reasoning:'   '}),/Reasoning is required/);assert.throws(()=>engine.submitProblem(student,{problemId:'motion-average-speed',answer:'5',reasoning:'distance divided by time',confidence:101}),/between 0 and 100/);db.close(); });
