import test from 'node:test';
import assert from 'node:assert/strict';
import { LearningStore } from '../src/store.js';
import { LearningEngine } from '../src/learning-engine.js';

test('real SQLite learner state survives a new engine instance', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const first = new LearningEngine(db); first.start(student); first.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100}); first.recordAttempt(student,'motion',true,'correct velocity reasoning'); const second = new LearningEngine(db); const snapshot = second.snapshot(student); assert.equal(snapshot.mastery.motion,100); assert.equal(snapshot.status,'learning'); assert.equal(snapshot.dueReviews.length,0); db.close(); });
test('recording mastery changes the durable learner model', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Test'); const engine = new LearningEngine(db); engine.start(student); const result = engine.recordAttempt(student,'arithmetic',true); assert.equal(result.mastery.arithmetic,100); assert.equal(result.dueReviews.length,0); db.close(); });
test('current concept cannot bypass requirements', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Test'); const engine = new LearningEngine(db); engine.start(student); assert.throws(() => engine.setCurrent(student,'forces'), /requirements/); db.close(); });
test('misconceptions are durable and can be resolved', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const engine = new LearningEngine(db); engine.start(student); const m = engine.recordMisconception(student,'motion','velocity-vs-speed','Confuses direction with scalar speed'); assert.equal(engine.listOpenMisconceptions(student).length,1); assert.equal(m.status,'open'); engine.resolveMisconception(m.id); assert.equal(engine.listOpenMisconceptions(student).length,0); db.close(); });
test('exact lesson resume state survives a new engine instance', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const engine = new LearningEngine(db); engine.start(student); engine.saveResume(student,'motion-lesson-1','problem-3',4); const resumed = new LearningEngine(db).snapshot(student); assert.deepEqual(resumed.resume && {lessonId:resumed.resume.lessonId,problemId:resumed.resume.problemId,step:resumed.resume.step},{lessonId:'motion-lesson-1',problemId:'problem-3',step:4}); db.close(); });
test('successful attempts schedule progressively spaced reviews', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const engine = new LearningEngine(db); engine.start(student); const first = engine.recordAttempt(student,'arithmetic',true); assert.equal(db.getDueReviews(student).length,0); const second = engine.recordAttempt(student,'arithmetic',true); const reviews = db.db.prepare('SELECT interval_days,repetitions FROM reviews WHERE student_id = ? AND concept_id = ?').get(student,'arithmetic') as {interval_days:number;repetitions:number}; assert.equal(reviews.interval_days,2); assert.equal(reviews.repetitions,2); assert.equal(first.dueReviews.length,0); assert.equal(second.dueReviews.length,0); db.close(); });
test('journey is derived from the same graph and learner state', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const engine = new LearningEngine(db); engine.start(student); let journey = engine.journey(student); assert.equal(journey.find(n => n.id === 'measurement')?.status,'locked'); db.setMastery(student,'arithmetic',100); db.setMastery(student,'measurement',100); journey = new LearningEngine(db).journey(student); assert.equal(journey.find(n => n.id === 'measurement')?.status,'mastered'); assert.equal(journey.find(n => n.id === 'motion')?.status,'locked'); db.close(); });
test('diagnostic evidence is weighted and persisted', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const engine = new LearningEngine(db); engine.start(student); const result = engine.diagnostic(student,[{conceptId:'measurement',score:60,kind:'diagnostic',difficulty:1},{conceptId:'measurement',score:100,kind:'transfer',difficulty:1}]); assert.equal(result.scores.measurement,83); assert.equal(result.confidence.measurement,0.78); assert.equal(db.getMastery(student).measurement,83); db.close(); });
test('diagnostic rejects impossible evidence', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const engine = new LearningEngine(db); engine.start(student); assert.throws(() => engine.diagnostic(student,[{conceptId:'measurement',score:101,kind:'diagnostic',difficulty:1}]), /between 0 and 100/); db.close(); });
test('remediation selects a blocking dependency and only resolves after a correct retry', () => { const db = new LearningStore(':memory:'); const student = db.ensureStudent('Ada'); const engine = new LearningEngine(db); engine.start(student); engine.placeByDemonstratedMastery(student,{arithmetic:100,measurement:100}); const m=engine.recordMisconception(student,'motion','velocity-vs-speed','Treats velocity as scalar speed'); const plan=engine.remediation(student,'motion'); assert.deepEqual(plan,{misconceptionId:m.id,sourceConcept:'motion',targetConcept:'graphs',reason:'misconception',retryRequired:true}); engine.retryRemediation(student,m.id,'graphs',false,'Still cannot read slope'); assert.equal(engine.listOpenMisconceptions(student).length,1); engine.retryRemediation(student,m.id,'graphs',true,'Reads slope correctly'); assert.equal(engine.listOpenMisconceptions(student).length,0); db.close(); });
