import { chooseNextPhysicsConcept, getConcept, missingRequirements } from '../curriculum.js';
import { diagnoseReasoning, mergeDiagnosticCodes } from '../diagnostics.js';
import { getInterventionPlan, getRemediationProblem } from '../interventions.js';
import type { RemediationVerdict } from '../interventions.js';
import { getReviewProblemForConcept } from '../reviews.js';
import { evaluateAnswer } from '../answer-evaluator.js';
import { evaluateRemediation } from '../remediation-evaluator.js';
import { selectIntervention, learnerFacingIntervention } from '../intervention-selection.js';
import { getLearnerTimeline } from '../learner-timeline.js';
import type { LearnerTimelineEvent } from '../learner-timeline.js';
import type { LearningStoreContract } from '../store-contract.js';
import type { EvidenceInput, InterventionRecord, MisconceptionRecord, ResumeState, ReviewRecord } from '../store-types.js';
import type { ReviewProblem } from '../reviews.js';

export type LearningStatus='new'|'diagnostic'|'learning';
export interface LearnerJourney{location:string;blocker:string|null;noticed:string|null;why:string|null;demonstratedRepair:string|null;readyFor:string|null;}
export interface LearnerSnapshot{studentId:number;status:LearningStatus;currentConcept:string|null;nextConcept:string|null;mastery:Record<string,number>;missingRequirements:string[];activeMisconceptions:MisconceptionRecord[];interventionQueue:InterventionRecord[];selectedIntervention:InterventionRecord|undefined;interventionMessage:{blocking:string;noticed:string;why:string}|undefined;dueReviews:ReviewRecord[];resume:ResumeState|undefined;journey:LearnerJourney;}
export interface AttemptInput extends Omit<EvidenceInput,'kind'>{correct:boolean;misconceptionCodes?:string[];misconceptionSeverity?:number;}
export interface RemediationInput{reasoning:string;answer:string;confidence?:number|null;hintUsed?:boolean;durationSeconds?:number|null;}
export interface ReviewResult{outcome:'retained'|'misconception_reopened'|'new_misconception'|'insufficient_evidence';problemId:string;attemptId:number;checkpointScore:number;snapshot:LearnerSnapshot;}
export interface RemediationResult{evaluation:ReturnType<typeof evaluateRemediation>;attemptId:number;snapshot:LearnerSnapshot;}

export class PostgresLearningEngine {
  constructor(private readonly store:LearningStoreContract) {}
  async start(studentId:number):Promise<LearnerSnapshot>{if(!(await this.store.getSession(studentId)))await this.store.saveSession(studentId,'diagnostic',null,0);return this.snapshot(studentId);}
  async snapshot(studentId:number):Promise<LearnerSnapshot>{
    const [session,mastery,allMisconceptions,allInterventions,dueReviews,resume]=await Promise.all([this.store.getSession(studentId),this.store.getMastery(studentId),this.store.listMisconceptions(studentId),this.store.listInterventions(studentId),this.store.listDueReviews(studentId),this.store.getResume(studentId)]);
    const next=chooseNextPhysicsConcept(mastery); const active=allMisconceptions.filter(m=>m.status==='active'); const queue=allInterventions.filter(i=>i.status==='queued'||i.status==='active');
    const selected=selectIntervention(active,queue); const selectedIntervention=selected?queue.find(i=>i.id===selected.interventionId):undefined; const selectedMisconception=selected?active.find(m=>m.code===selected.misconceptionCode):undefined;
    const message=selected&&selectedMisconception?learnerFacingIntervention(selectedMisconception,selected):undefined; const repaired=await this.demonstratedRepair(allMisconceptions);
    return {studentId,status:(session?.status??'new') as LearningStatus,currentConcept:session?.currentConcept??null,nextConcept:next?.id??null,mastery,missingRequirements:next?missingRequirements(mastery,next.id):[],activeMisconceptions:active,interventionQueue:queue,selectedIntervention,interventionMessage:message,dueReviews:dueReviews,resume,journey:this.journey(session?.currentConcept??selectedIntervention?.conceptId??null,next?.id??null,selectedMisconception,selectedIntervention,message,repaired)};
  }
  private async demonstratedRepair(misconceptions:MisconceptionRecord){for(const m of misconceptions.filter(x=>x.status==='resolved').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))){const s=await this.store.getMisconceptionState(m.id);if(s&&s.positiveEvidence>=2&&s.confidence<=30)return `You have demonstrated repair of ${m.code} with repeated positive evidence.`;}return null;}
  private journey(currentConcept:string|null,nextConcept:string|null,m:MisconceptionRecord|undefined,i:InterventionRecord|undefined,message:{blocking:string;noticed:string;why:string}|undefined,repaired:string|null):LearnerJourney{if(i&&message)return{location:currentConcept??i.conceptId,blocker:message.blocking,noticed:message.noticed,why:message.why,demonstratedRepair:repaired,readyFor:null};if(m)return{location:currentConcept??m.conceptId,blocker:`${m.code} is still active`,noticed:'Vita has evidence of a recurring reasoning pattern.',why:'The next task is targeted repair rather than restarting the whole lesson.',demonstratedRepair:repaired,readyFor:null};return{location:currentConcept??nextConcept??'learning',blocker:null,noticed:null,why:null,demonstratedRepair:repaired,readyFor:nextConcept};}
  async setCurrent(studentId:number,conceptId:string){getConcept(conceptId);const missing=missingRequirements(await this.store.getMastery(studentId),conceptId);if(missing.length)throw new Error(`Cannot start ${conceptId}; requirements not yet demonstrated: ${missing.join(', ')}`);await this.store.saveSession(studentId,'learning',conceptId,0);return this.snapshot(studentId);}
  async recordStructuredAttempt(studentId:number,conceptId:string,input:AttemptInput){getConcept(conceptId);const evidenceId=await this.store.addEvidence(studentId,conceptId,{kind:'attempt',value:input.correct?1:0,note:input.note??'',lessonId:input.lessonId??null,problemId:input.problemId??null,reasoning:input.reasoning??null,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null});await this.store.recordMastery(studentId,conceptId,input.correct);const findings=mergeDiagnosticCodes(conceptId,input.reasoning,input.misconceptionCodes,input.misconceptionSeverity??1);for(const finding of findings){const m=await this.store.upsertMisconception(studentId,conceptId,finding.code,finding.severity,evidenceId);const plan=getInterventionPlan(finding);const first=plan?.problems.find(p=>p.stage==='discrimination');if(plan&&first)await this.store.queueIntervention(studentId,m.id,conceptId,plan.prerequisiteConceptId,first.id,'discrimination',plan.strategy);}await this.store.saveSession(studentId,'learning',conceptId,0);return this.snapshot(studentId);}
  async diagnoseAttempt(conceptId:string,reasoning:string){return diagnoseReasoning(conceptId,reasoning);}
  async nextIntervention(studentId:number){const queue=(await this.store.listInterventions(studentId)).filter(i=>i.status==='queued'||i.status==='active');const selected=selectIntervention((await this.store.listMisconceptions(studentId)).filter(m=>m.status==='active'),queue);if(!selected)return undefined;const intervention=queue.find(i=>i.id===selected.interventionId);if(intervention?.status==='queued')await this.store.activateIntervention(intervention.id);return intervention?this.store.getIntervention(intervention.id):undefined;}
  async submitRemediationAttempt(studentId:number,interventionId:number,input:RemediationInput):Promise<RemediationResult>{const intervention=await this.store.getIntervention(interventionId);if(!intervention||intervention.studentId!==studentId)throw new Error('Unknown learner intervention');const problem=getRemediationProblem(intervention.problemId);if(problem.stage!==intervention.stage)throw new Error('Intervention stage does not match remediation problem');if(intervention.status==='queued')await this.store.activateIntervention(interventionId);const answerEvaluation=evaluateAnswer(problem,input.answer,input.reasoning);const correct=answerEvaluation.correct;const evidenceId=await this.store.addEvidence(studentId,problem.conceptId,{kind:'remediation_attempt',value:correct?1:0,problemId:problem.id,reasoning:input.reasoning,note:input.answer,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null});const evaluation=evaluateRemediation(problem,input.reasoning,input.answer,correct);const attemptId=await this.store.addRemediationAttempt(interventionId,evidenceId,evaluation.verdict,evaluation.checkpointScore);const m=(await this.store.listMisconceptions(studentId,problem.conceptId)).find(x=>x.code===problem.misconceptionCode);if(m)await this.store.recordMisconceptionSignal(m.id,evaluation.verdict as RemediationVerdict);
    if(evaluation.verdict==='repaired'&&intervention.stage==='discrimination'){const plan=getInterventionPlan({code:problem.misconceptionCode});const next=plan?.problems.find(p=>p.stage==='transfer');if(next)await this.store.queueIntervention(studentId,intervention.misconceptionId,problem.conceptId,problem.prerequisiteConceptId,next.id,'transfer',plan!.strategy);await this.store.completeIntervention(interventionId);}
    else if(evaluation.verdict==='repaired'&&intervention.stage==='transfer'){await this.store.completeIntervention(interventionId);if(m){const state=await this.store.getMisconceptionState(m.id);if(state&&state.positiveEvidence>=2&&state.confidence<=30)await this.store.markMisconceptionRepaired(studentId,m.id);}await this.store.scheduleReview(studentId,problem.conceptId,evaluation.checkpointScore);}
    if(evaluation.newMisconceptions.length){const all=diagnoseReasoning(problem.conceptId,input.reasoning);for(const code of evaluation.newMisconceptions){const finding=all.find(f=>f.code===code);const plan=finding&&getInterventionPlan(finding);if(finding&&plan){const first=plan.problems.find(p=>p.stage==='discrimination');if(first){const nm=await this.store.upsertMisconception(studentId,problem.conceptId,code,finding.severity,evidenceId);await this.store.queueIntervention(studentId,nm.id,problem.conceptId,problem.prerequisiteConceptId,first.id,'discrimination',plan.strategy);}}}}
    return{evaluation,attemptId,snapshot:await this.snapshot(studentId)};}
  async nextReview(studentId:number,at=new Date()){return (await this.store.listDueReviews(studentId,at.toISOString()))[0];}
  async getReviewProblem(studentId:number,at=new Date()):Promise<ReviewProblem|undefined>{const review=await this.nextReview(studentId,at);return review?getReviewProblemForConcept(review.conceptId):undefined;}
  async submitReviewAttempt(studentId:number,input:RemediationInput,at=new Date()):Promise<ReviewResult>{const review=await this.nextReview(studentId,at);if(!review)throw new Error('No review is due for this learner');const problem=getReviewProblemForConcept(review.conceptId);if(!problem)throw new Error(`No review problem is available for concept: ${review.conceptId}`);const answerEvaluation=evaluateAnswer(problem,input.answer,input.reasoning);const correct=answerEvaluation.correct;const evidenceId=await this.store.addEvidence(studentId,problem.conceptId,{kind:'review_attempt',value:correct?1:0,problemId:problem.id,reasoning:input.reasoning,note:input.answer,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null});const evaluation=evaluateRemediation(problem,input.reasoning,input.answer,correct);const outcome:ReviewResult['outcome']=evaluation.verdict==='new_misconception'?'new_misconception':evaluation.verdict==='repaired'?'retained':!correct?'misconception_reopened':evaluation.verdict==='still_present'?'misconception_reopened':'insufficient_evidence';const m=(await this.store.listMisconceptions(studentId,problem.conceptId)).find(x=>x.code===problem.misconceptionCode);if(m)await this.store.recordMisconceptionSignal(m.id,outcome==='misconception_reopened'?'still_present':evaluation.verdict as RemediationVerdict);await this.store.recordMastery(studentId,problem.conceptId,correct);const attemptId=await this.store.addReviewAttempt(studentId,problem.conceptId,problem.id,evidenceId,outcome,evaluation.checkpointScore);if(outcome==='retained'){if(m){const state=await this.store.getMisconceptionState(m.id);if(state&&state.confidence<=30&&state.positiveEvidence>=2)await this.store.markMisconceptionRepaired(studentId,m.id);}await this.store.scheduleReview(studentId,problem.conceptId,evaluation.checkpointScore,at);}else{await this.store.scheduleReview(studentId,problem.conceptId,Math.min(evaluation.checkpointScore,0.5),at);for(const finding of mergeDiagnosticCodes(problem.conceptId,input.reasoning)){const plan=getInterventionPlan(finding);if(plan){const target=(await this.store.listMisconceptions(studentId,problem.conceptId)).find(x=>x.code===finding.code)??await this.store.upsertMisconception(studentId,problem.conceptId,finding.code,finding.severity,evidenceId);const first=plan.problems.find(p=>p.stage==='discrimination');if(first)await this.store.queueIntervention(studentId,target.id,problem.conceptId,problem.prerequisiteConceptId,first.id,'discrimination',plan.strategy);}}}return{outcome,problemId:problem.id,attemptId,checkpointScore:evaluation.checkpointScore,snapshot:await this.snapshot(studentId)};}
  async timeline(studentId:number):Promise<LearnerTimelineEvent[]>{return getLearnerTimeline(this.store as never,studentId);}
  async saveResume(studentId:number,lessonId:string|null,problemId:string|null,step:number,state:unknown=null){await this.store.saveResume(studentId,lessonId,problemId,step,state);return this.snapshot(studentId);}
}
