import { chooseNextPhysicsConcept, getConcept, missingRequirements } from '../curriculum.js';
import { diagnoseReasoning, mergeDiagnosticCodes } from '../diagnostics.js';
import { getInterventionPlan, getRemediationProblem } from '../interventions.js';
import type { RemediationVerdict } from '../interventions.js';
import { getReviewProblemForConcept } from '../reviews.js';
import { evaluateAnswer } from '../answer-evaluator.js';
import { evaluateRemediation } from '../remediation-evaluator.js';
import { selectIntervention, learnerFacingIntervention } from '../intervention-selection.js';
import type { LearnerTimelineEvent } from '../learner-timeline.js';
import { getPostgresLearnerTimeline } from '../infrastructure/postgres-timeline.js';
import type { LearningStoreContract } from '../store-contract.js';
import type { EvidenceInput, InterventionRecord, MisconceptionRecord, ResumeState, ReviewRecord } from '../store-types.js';
import type { ReviewProblem } from '../reviews.js';
export type LearningStatus='new'|'diagnostic'|'learning';
export interface LearnerJourney{location:string;blocker:string|null;noticed:string|null;why:string|null;demonstratedRepair:string|null;readyFor:string|null;}
export interface LearnerSnapshot{studentId:number;status:LearningStatus;currentConcept:string|null;nextConcept:string|null;mastery:Record<string,number>;missingRequirements:string[];activeMisconceptions:MisconceptionRecord[];interventionQueue:InterventionRecord[];selectedIntervention:InterventionRecord|undefined;interventionMessage:{blocking:string;noticed:string;why:string}|undefined;dueReviews:ReviewRecord[];resume:ResumeState|undefined;journey:LearnerJourney;}
export interface AttemptInput extends Omit<EvidenceInput,'kind'>{correct:boolean;misconceptionCodes?:string[];misconceptionSeverity?:number;}
export interface RemediationInput{reasoning:string;answer:string;confidence?:number|null;hintUsed?:boolean;durationSeconds?:number|null;}
export interface ReviewResult{outcome:'retained'|'misconception_reopened'|'new_misconception'|'insufficient_evidence';problemId:string;attemptId:number;checkpointScore:number;snapshot:LearnerSnapshot;}
export interface RemediationResult{evaluation:ReturnType<typeof evaluateRemediation>;attemptId:number;snapshot:LearnerSnapshot;}
export class PostgresLearningEngine{
 constructor(private readonly store:LearningStoreContract){}
 async start(id:number){if(!(await this.store.getSession(id)))await this.store.saveSession(id,'diagnostic',null,0);return this.snapshot(id);}
 async snapshot(id:number):Promise<LearnerSnapshot>{const[session,mastery,misconceptions,interventions,reviews,resume]=await Promise.all([this.store.getSession(id),this.store.getMastery(id),this.store.listMisconceptions(id),this.store.listInterventions(id),this.store.listDueReviews(id),this.store.getResume(id)]);const next=chooseNextPhysicsConcept(mastery);const active=misconceptions.filter(x=>x.status==='active');const queue=interventions.filter(x=>x.status==='queued'||x.status==='active');const selected=selectIntervention(active,queue);const selectedIntervention=selected?queue.find(x=>x.id===selected.interventionId):undefined;const selectedMisconception=selected?active.find(x=>x.code===selected.misconceptionCode):undefined;const message=selected&&selectedMisconception?learnerFacingIntervention(selectedMisconception,selected):undefined;const repaired=await this.findDemonstratedRepair(misconceptions);return{studentId:id,status:(session?.status??'new') as LearningStatus,currentConcept:session?.currentConcept??null,nextConcept:next?.id??null,mastery,missingRequirements:next?missingRequirements(mastery,next.id):[],activeMisconceptions:active,interventionQueue:queue,selectedIntervention,interventionMessage:message,dueReviews:reviews,resume,journey:this.journey(session?.currentConcept??selectedIntervention?.conceptId??null,next?.id??null,selectedMisconception,selectedIntervention,message,repaired)};}
 private async findDemonstratedRepair(records: MisconceptionRecord[]):Promise<string|null>{const resolved=records.filter((record:MisconceptionRecord)=>record.status==='resolved').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));for(const record of resolved){const state=await this.store.getMisconceptionState(record.id);if(state&&state.positiveEvidence>=2&&state.confidence<=30)return`You have demonstrated repair of ${record.code} with repeated positive evidence.`;}return null;}
 private journey(current:string|null,next:string|null,m:MisconceptionRecord|undefined,i:InterventionRecord|undefined,msg:{blocking:string;noticed:string;why:string}|undefined,repaired:string|null):LearnerJourney{if(i&&msg)return{location:current??i.conceptId,blocker:msg.blocking,noticed:msg.noticed,why:msg.why,demonstratedRepair:repaired,readyFor:null};if(m)return{location:current??m.conceptId,blocker:`${m.code} is still active`,noticed:'Vita has evidence of a recurring reasoning pattern.',why:'The next task is targeted repair rather than restarting the whole lesson.',demonstratedRepair:repaired,readyFor:null};return{location:current??next??'learning',blocker:null,noticed:null,why:null,demonstratedRepair:repaired,readyFor:next};}
 async setCurrent(id:number,concept:string){getConcept(concept);const missing=missingRequirements(await this.store.getMastery(id),concept);if(missing.length)throw new Error(`Cannot start ${concept}; requirements not yet demonstrated: ${missing.join(', ')}`);await this.store.saveSession(id,'learning',concept,0);return this.snapshot(id);}
 async recordStructuredAttempt(id:number,concept:string,input:AttemptInput){getConcept(concept);const evidenceInput:EvidenceInput={kind:'attempt',value:input.correct?1:0,note:input.note??'',lessonId:input.lessonId??null,problemId:input.problemId??null,reasoning:input.reasoning??null,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null};const evidence=this.store.recordAttemptEvidenceAndMastery?await this.store.recordAttemptEvidenceAndMastery(id,concept,evidenceInput,input.correct):await this.store.addEvidence(id,concept,evidenceInput);if(!this.store.recordAttemptEvidenceAndMastery)await this.store.recordMastery(id,concept,input.correct);for(const finding of mergeDiagnosticCodes(concept,input.reasoning,input.misconceptionCodes,input.misconceptionSeverity??1)){const m=await this.store.upsertMisconception(id,concept,finding.code,finding.severity,evidence);const plan=getInterventionPlan(finding);const first=plan?.problems.find(p=>p.stage==='discrimination');if(plan&&first)await this.store.queueIntervention(id,m.id,concept,plan.prerequisiteConceptId,first.id,'discrimination',plan.strategy);}await this.store.saveSession(id,'learning',concept,0);return this.snapshot(id);}
 async diagnoseAttempt(concept:string,reasoning:string){return diagnoseReasoning(concept,reasoning);}
 async nextIntervention(id:number){const queue=(await this.store.listInterventions(id)).filter(x=>x.status==='queued'||x.status==='active');const selected=selectIntervention((await this.store.listMisconceptions(id)).filter(x=>x.status==='active'),queue);if(!selected)return undefined;const intervention=queue.find(x=>x.id===selected.interventionId);if(intervention?.status==='queued')await this.store.activateIntervention(intervention.id);return intervention?this.store.getIntervention(intervention.id):undefined;}
 async submitRemediationAttempt(id:number,interventionId:number,input:RemediationInput):Promise<RemediationResult>{const intervention=await this.store.getIntervention(interventionId);if(!intervention||intervention.studentId!==id)throw new Error('Unknown learner intervention');const problem=getRemediationProblem(intervention.problemId);if(problem.stage!==intervention.stage)throw new Error('Intervention stage does not match remediation problem');if(intervention.status==='queued')await this.store.activateIntervention(interventionId);const ae=evaluateAnswer(problem,input.answer,input.reasoning),evidence=await this.store.addEvidence(id,problem.conceptId,{kind:'remediation_attempt',value:ae.correct?1:0,problemId:problem.id,reasoning:input.reasoning,note:input.answer,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null});const evaluation=evaluateRemediation(problem,input.reasoning,input.answer,ae.correct);const attemptId=await this.store.addRemediationAttempt(interventionId,evidence,evaluation.verdict,evaluation.checkpointScore);const m=(await this.store.listMisconceptions(id,problem.conceptId)).find(x=>x.code===problem.misconceptionCode);if(m)await this.store.recordMisconceptionSignal(m.id,evaluation.verdict as RemediationVerdict);if(evaluation.verdict==='repaired'&&intervention.stage==='discrimination'){const plan=getInterventionPlan({code:problem.misconceptionCode});const next=plan?.problems.find(p=>p.stage==='transfer');if(next)await this.store.queueIntervention(id,intervention.misconceptionId,problem.conceptId,problem.prerequisiteConceptId,next.id,'transfer',plan!.strategy);await this.store.completeIntervention(interventionId);}else if(evaluation.verdict==='repaired'&&intervention.stage==='transfer'){await this.store.completeIntervention(interventionId);if(m){const s=await this.store.getMisconceptionState(m.id);if(s&&s.positiveEvidence>=2&&s.confidence<=30)await this.store.markMisconceptionRepaired(id,m.id);}await this.store.scheduleReview(id,problem.conceptId,evaluation.checkpointScore);}return{evaluation,attemptId,snapshot:await this.snapshot(id)};}
 async nextReview(id:number,at=new Date()){return(await this.store.listDueReviews(id,at.toISOString()))[0];}
 async getReviewProblem(id:number,at=new Date()):Promise<ReviewProblem|undefined>{const r=await this.nextReview(id,at);return r?getReviewProblemForConcept(r.conceptId):undefined;}
 async submitReviewAttempt(id:number,input:RemediationInput,at=new Date()):Promise<ReviewResult>{const review=await this.nextReview(id,at);if(!review)throw new Error('No review is due for this learner');const problem=getReviewProblemForConcept(review.conceptId);if(!problem)throw new Error(`No review problem is available for concept: ${review.conceptId}`);const ae=evaluateAnswer(problem,input.answer,input.reasoning),evidence=await this.store.addEvidence(id,problem.conceptId,{kind:'review_attempt',value:ae.correct?1:0,problemId:problem.id,reasoning:input.reasoning,note:input.answer,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null});const evaluation=evaluateRemediation(problem,input.reasoning,input.answer,ae.correct);const outcome:ReviewResult['outcome']=evaluation.verdict==='new_misconception'?'new_misconception':evaluation.verdict==='repaired'?'retained':!ae.correct?'misconception_reopened':evaluation.verdict==='still_present'?'misconception_reopened':'insufficient_evidence';const m=(await this.store.listMisconceptions(id,problem.conceptId)).find(x=>x.code===problem.misconceptionCode);if(m)await this.store.recordMisconceptionSignal(m.id,outcome==='misconception_reopened'?'still_present':evaluation.verdict as RemediationVerdict);await this.store.recordMastery(id,problem.conceptId,ae.correct);const attemptId=await this.store.addReviewAttempt(id,problem.conceptId,problem.id,evidence,outcome,evaluation.checkpointScore);await this.store.scheduleReview(id,problem.conceptId,outcome==='retained'?evaluation.checkpointScore:Math.min(evaluation.checkpointScore,.5),at);return{outcome,problemId:problem.id,attemptId,checkpointScore:evaluation.checkpointScore,snapshot:await this.snapshot(id)};}
 async timeline(id:number):Promise<LearnerTimelineEvent[]>{return getPostgresLearnerTimeline(this.store as LearningStoreContract & {query:(sql:string,params?:unknown[])=>Promise<{rows:Record<string,unknown>[]} >},id);}
 async saveResume(id:number,lessonId:string|null,problemId:string|null,step:number,state:unknown=null){await this.store.saveResume(id,lessonId,problemId,step,state);return this.snapshot(id);}
}
