import type { DiagnosticFinding } from './diagnostics.js';
export type InterventionStage='discrimination'|'transfer';
export type InterventionStatus='queued'|'active'|'completed'|'blocked';
export type RemediationVerdict='repaired'|'still_present'|'new_misconception'|'insufficient_evidence';
export interface ReasoningCheckpoint{id:string;label:string;expected:string;}
export interface RemediationProblem{id:string;misconceptionCode:string;conceptId:string;prerequisiteConceptId:string;stage:InterventionStage;prompt:string;givens:readonly string[];expectedReasoning:readonly string[];checkpoints:readonly ReasoningCheckpoint[];answer:string;}
export interface InterventionPlan{misconceptionCode:string;strategy:string;prerequisiteConceptId:string;problems:readonly RemediationProblem[];}
const PROBLEMS:readonly RemediationProblem[]=[
{id:'force-motion-discrimination-1',misconceptionCode:'force_causes_motion',conceptId:'forces',prerequisiteConceptId:'motion',stage:'discrimination',prompt:'A hockey puck slides across level, nearly frictionless ice at constant velocity. What is the net horizontal force on the puck? Explain why the puck can keep moving even though the net force is zero.',givens:['Straight-line motion.','Constant velocity.','Negligible horizontal friction.'],expectedReasoning:['Constant velocity means zero acceleration.','Use F_net = ma.','Net force is zero.','Force changes velocity through acceleration; it does not sustain constant velocity.'],checkpoints:[{id:'velocity',label:'Velocity',expected:'Constant velocity means acceleration is zero.'},{id:'net-force',label:'Net force',expected:'Zero acceleration implies zero net force.'},{id:'causation',label:'Causal model',expected:'Net force changes velocity; it is not required to sustain constant velocity.'}],answer:'The net horizontal force is 0 N because constant velocity means zero acceleration. Motion does not require a continuing net force.'},
{id:'force-motion-transfer-1',misconceptionCode:'force_causes_motion',conceptId:'forces',prerequisiteConceptId:'motion',stage:'transfer',prompt:'A 2 kg cart moves east at 3 m/s. A horizontal net force of 4 N east acts on it for 2 s. Find its acceleration and final velocity. Explain what the force changes.',givens:['m = 2 kg','u = 3 m/s east','F_net = 4 N east','t = 2 s'],expectedReasoning:['Apply F_net = ma.','a = 2 m/s² east.','Use v = u + at.','v = 7 m/s east.','The force changes velocity by producing acceleration.'],checkpoints:[{id:'equation',label:'Force equation',expected:'Use net force to determine acceleration.'},{id:'units',label:'Units',expected:'Acceleration is m/s² and velocity is m/s.'},{id:'change',label:'Change in motion',expected:'The force changes velocity through acceleration.'}],answer:'a = 2 m/s² east; v = 7 m/s east.'},
{id:'heat-temperature-discrimination-1',misconceptionCode:'heat_equals_temperature',conceptId:'temperature_heat',prerequisiteConceptId:'energy',stage:'discrimination',prompt:'Two identical cups contain equal masses of water. Cup A is at 20 °C and Cup B is at 60 °C. Is temperature itself a quantity of heat contained in the water? Explain what temperature and heat mean here.',givens:['Equal water masses.','20 °C and 60 °C.'],expectedReasoning:['Temperature describes thermal state/microscopic energy distribution.','Heat is energy transferred because of temperature difference.','Temperature is not an amount of heat.'],checkpoints:[{id:'temperature',label:'Temperature',expected:'Temperature characterizes thermal state.'},{id:'heat',label:'Heat',expected:'Heat is energy transferred due to temperature difference.'}],answer:'No. Temperature is not an amount of heat; heat is energy transferred because of a temperature difference.'},
{id:'heat-temperature-transfer-1',misconceptionCode:'heat_equals_temperature',conceptId:'temperature_heat',prerequisiteConceptId:'energy',stage:'transfer',prompt:'A 0.50 kg metal block at 80 °C is placed in contact with a 1.0 kg block at 20 °C. After equilibrium both are 40 °C. Did the final 40 °C become “the amount of heat” in either block? Describe what happened to energy.',givens:['Initial temperatures: 80 °C and 20 °C.','Final equilibrium temperature: 40 °C.'],expectedReasoning:['Temperature describes the thermal state.','Energy was transferred from the hotter block to the cooler block.','Heat names the transfer, not a substance stored at 40 °C.'],checkpoints:[{id:'temperature',label:'Temperature',expected:'Temperature characterizes thermal state.'},{id:'heat',label:'Heat',expected:'Heat is energy transferred due to temperature difference.'}],answer:'No. The 40 °C is a final thermal state; energy was transferred from the hotter block to the cooler one.'},
{id:'energy-force-discrimination-1',misconceptionCode:'energy_as_force',conceptId:'energy',prerequisiteConceptId:'forces',stage:'discrimination',prompt:'A 5 N horizontal force pushes a box 4 m in the direction of the force. Calculate the work done and explain why work and force are not the same physical quantity.',givens:['F = 5 N','d = 4 m','Force parallel to displacement.'],expectedReasoning:['Force describes an interaction.','Use W = Fd.','W = 20 J.','Force is measured in N; work/energy in J.'],checkpoints:[{id:'interaction',label:'Force',expected:'Force describes an interaction and uses newtons.'},{id:'work',label:'Work',expected:'Work is energy transferred by force through displacement.'},{id:'units',label:'Units',expected:'Force is N; work and energy are J.'}],answer:'W = 20 J; force and work are different quantities.'},
{id:'energy-force-transfer-1',misconceptionCode:'energy_as_force',conceptId:'energy',prerequisiteConceptId:'forces',stage:'transfer',prompt:'A 10 N force acts on a box while it moves 3 m in the force direction. The box gains 30 J of kinetic energy from this interaction. What is the force, and what is the energy change? Explain why the two values cannot be treated as the same quantity.',givens:['F = 10 N','d = 3 m','Kinetic-energy gain = 30 J.'],expectedReasoning:['Force is an interaction measured in N.','Work transfers energy through displacement.','W = Fd = 30 J.','30 N and 30 J have different meanings and units.'],checkpoints:[{id:'interaction',label:'Force',expected:'Force describes an interaction and has units of newtons.'},{id:'work',label:'Work',expected:'Work transfers energy through displacement.'},{id:'units',label:'Units',expected:'N and J are different units.'}],answer:'The force is 10 N and the work/energy transfer is 30 J.'},
{id:'direction-scalar-discrimination-1',misconceptionCode:'direction_as_scalar',conceptId:'forces',prerequisiteConceptId:'vectors',stage:'discrimination',prompt:'A 10 N force acts east while a 6 N force acts west on the same object. Find the net force and state its direction. Explain why simply adding 10 + 6 is not sufficient.',givens:['10 N east','6 N west'],expectedReasoning:['Choose a positive direction.','Represent west as negative.','10 - 6 = 4 N.','Net force is 4 N east.'],checkpoints:[{id:'direction',label:'Direction',expected:'Opposite directions require signed/vector treatment.'},{id:'result',label:'Net force',expected:'Net force is 4 N east.'}],answer:'The net force is 4 N east.'},
{id:'direction-scalar-transfer-1',misconceptionCode:'direction_as_scalar',conceptId:'forces',prerequisiteConceptId:'vectors',stage:'transfer',prompt:'A 3 N force acts north and a 4 N force acts east on a 1 kg object. Find the magnitude and direction of the net force. Show why the two forces cannot simply be added as 3 + 4 N.',givens:['3 N north','4 N east','m = 1 kg'],expectedReasoning:['Recognize perpendicular vector components.','Use Pythagoras: sqrt(3²+4²) = 5 N.','Direction is arctan(3/4) north of east.','State that direction matters.'],checkpoints:[{id:'direction',label:'Direction',expected:'Perpendicular directions require vector components.'},{id:'result',label:'Net force',expected:'Magnitude is 5 N, directed northeast.'}],answer:'The net force has magnitude 5 N, at about 36.9° north of east.'},
{id:'ratio-additive-discrimination-1',misconceptionCode:'ratio_additive',conceptId:'fractions',prerequisiteConceptId:'arithmetic',stage:'discrimination',prompt:'A recipe uses flour and sugar in a 3:2 ratio. If the recipe is doubled, how much flour is needed when the original recipe used 6 cups? Explain why doubling preserves the ratio.',givens:['Flour:sugar = 3:2','Original flour = 6 cups','Scale factor = 2'],expectedReasoning:['Recognize multiplicative scaling.','Double 6 cups to get 12 cups.','Both quantities scale by the same factor.'],checkpoints:[{id:'scale',label:'Scale factor',expected:'Doubling means multiplying by 2.'},{id:'relationship',label:'Ratio relationship',expected:'A ratio expresses a multiplicative relationship.'}],answer:'12 cups.'},
{id:'ratio-additive-transfer-1',misconceptionCode:'ratio_additive',conceptId:'fractions',prerequisiteConceptId:'arithmetic',stage:'transfer',prompt:'A map scale is 1:50,000. A road measures 3 cm on the map. Estimate its real length in kilometres. Explain why the scale is multiplied rather than added.',givens:['Scale = 1:50,000','Map distance = 3 cm'],expectedReasoning:['Use the multiplicative scale factor 50,000.','3 × 50,000 = 150,000 cm.','Convert to 1.5 km.','Explain that ratios scale quantities multiplicatively.'],checkpoints:[{id:'scale',label:'Scale factor',expected:'Multiply by the scale factor.'},{id:'relationship',label:'Ratio relationship',expected:'A ratio expresses a multiplicative relationship.'}],answer:'150,000 cm = 1.5 km.'}
];
const PLANS:Readonly<Record<string,InterventionPlan>>={
force_causes_motion:{misconceptionCode:'force_causes_motion',prerequisiteConceptId:'motion',strategy:'Contrast constant velocity with acceleration, then require transfer to a numerical Newton-law problem.',problems:PROBLEMS.filter(p=>p.misconceptionCode==='force_causes_motion')},
heat_equals_temperature:{misconceptionCode:'heat_equals_temperature',prerequisiteConceptId:'energy',strategy:'Separate thermal state from energy transfer, then test the distinction in a new thermal context.',problems:PROBLEMS.filter(p=>p.misconceptionCode==='heat_equals_temperature')},
energy_as_force:{misconceptionCode:'energy_as_force',prerequisiteConceptId:'forces',strategy:'Contrast interaction (force) with transferred energy (work), including units and equations.',problems:PROBLEMS.filter(p=>p.misconceptionCode==='energy_as_force')},
direction_as_scalar:{misconceptionCode:'direction_as_scalar',prerequisiteConceptId:'vectors',strategy:'Make direction operational through signed components before returning to physical vector combinations.',problems:PROBLEMS.filter(p=>p.misconceptionCode==='direction_as_scalar')},
ratio_additive:{misconceptionCode:'ratio_additive',prerequisiteConceptId:'arithmetic',strategy:'Repair the multiplicative meaning of ratios using scale factors before returning to proportional physics problems.',problems:PROBLEMS.filter(p=>p.misconceptionCode==='ratio_additive')}
};
export function getInterventionPlan(finding:Pick<DiagnosticFinding,'code'>):InterventionPlan|undefined{return PLANS[finding.code];}
export function getRemediationProblem(problemId:string):RemediationProblem{const p=PROBLEMS.find(x=>x.id===problemId);if(!p)throw new Error(`Unknown remediation problem: ${problemId}`);return p;}
export function getAllRemediationProblems():readonly RemediationProblem[]{return PROBLEMS;}
