import { chooseNextPhysicsConcept, getConcept, missingRequirements } from './curriculum.js';
import { diagnoseReasoning, mergeDiagnosticCodes } from './diagnostics.js';
import { getInterventionPlan, getRemediationProblem } from './interventions.js';
import type { RemediationVerdict } from './interventions.js';
import { getReviewProblemForConcept } from './reviews.js';
import type { ReviewProblem } from './reviews.js';
import { evaluateRemediation } from './remediation-evaluator.js';
import { selectIntervention, learnerFacingIntervention } from './intervention-selection.js';
import { LearningStore } from './store.js';
import type { EvidenceInput, InterventionRecord, MisconceptionRecord, ResumeState, ReviewRecord } from './store.js';

export type LearningStatus='new'|'diagnostic'|'learning';
export interface LearnerJourney{location:string;blocker:string|null;noticed:string|null;why:string|null;demonstratedRepair:string|null;readyFor:string|null;}
export interface LearnerSnapshot{studentId:number;status:LearningStatus;currentConcept:string|null;nextConcept:string|null;mastery:Record<string,number>;missingRequirements:string[];activeMisconceptions:MisconceptionRecord[];interventionQueue:InterventionRecord[];selectedIntervention:InterventionRecord|undefined;interventionMessage:{blocking:string;noticed:string;why:string}|undefined;dueReviews:ReviewRecord[];resume:ResumeState|undefined;journey:LearnerJourney;}
export interface AttemptInput extends Omit<EvidenceInput,'kind'>{correct:boolean;misconceptionCodes?:string[];misconceptionSeverity?:number;}
export interface RemediationInput{reasoning:string;answer:string;correct:boolean;confidence?:number|null;hintUsed?:boolean;durationSeconds?:number|null;}
export interface ReviewInput extends RemediationInput{}
export interface ReviewResult{outcome:'retained'|'misconception_reopened'|'new_misconception'|'insufficient_evidence';problemId:string;attemptId:number;checkpointScore:number;snapshot:LearnerSnapshot;}
export interface RemediationResult{evaluation:ReturnType<typeof evaluateRemediation>;attemptId:number;snapshot:LearnerSnapshot;}

export class LearningEngine{
 constructor(private readonly store:LearningStore){}
 start(studentId:number):LearnerSnapshot{const existing=this.store.getSession(studentId);if(!existing)this.store.saveSession(studentId,'diagnostic',null,0);return this.snapshot(studentId);}
 snapshot(studentId:number):LearnerSnapshot{const session=this.store.getSession(studentId);const mastery=this.store.getMastery(studentId);const next=chooseNextPhysicsConcept(mastery);const active=this.store.listMisconceptions(studentId).filter(m=>m.status==='active');const queue=this.store.listInterventions(studentId).filter(i=>i.status==='queued'||i.status==='active');const selected=selectIntervention(active,queue);const selectedIntervention=selected?queue.find(i=>i.id===selected.interventionId):undefined;const selectedMisconception=selected?active.find(m=>m.code===selected.misconceptionCode):undefined;const message=selected&&selectedMisconception?learnerFacingIntervention(selectedMisconception,selected):undefined;return{studentId,status:(session?.status??'new') as LearningStatus,currentConcept:session?.currentConcept??null,nextConcept:next?.id??null,mastery,missingRequirements:next?missingRequirements(mastery,next.id):[],activeMisconceptions:active,interventionQueue:queue,selectedIntervention,interventionMessage:message,dueReviews:this.store.listDueReviews(studentId),resume:this.store.getResume(studentId),journey:this.journey(session?.currentConcept??null,next?.id??null,selectedMisconception,selectedIntervention,message)};}
 private journey(currentConcept:string|null,nextConcept:string|null,misconception:MisconceptionRecord|undefined,intervention:InterventionRecord|undefined,message:{blocking:string;noticed:string;why:string}|undefined):LearnerJourney{if(intervention&&message)return{location:currentConcept??intervention.conceptId,blocker:message.blocking,noticed:message.noticed,why:message.why,demonstratedRepair:null,readyFor:null};if(misconception&&misconception.status==='active')return{location:currentConcept??misconception.conceptId,blocker:`${misconception.code} is still active`,noticed:'Vita has evidence of a recurring reasoning pattern.',why:'The next task is targeted repair rather than restarting the whole lesson.',demonstratedRepair:null,readyFor:null};return{location:currentConcept??nextConcept??'learning',blocker:null,noticed:null,why:null,demonstratedRepair:null,readyFor:nextConcept};}
 setCurrent(studentId:number,conceptId:string):void{getConcept(conceptId);const missing=missingRequirements(this.store.getMastery(studentId),conceptId);if(missing.length)throw new Error(`Cannot start ${conceptId}; requirements not yet demonstrated: ${missing.join(', ')}`);this.store.saveSession(studentId,'learning',conceptId,0);}
 recordAttempt(studentId:number,conceptId:string,correct:boolean,note=''):LearnerSnapshot{return this.recordStructuredAttempt(studentId,conceptId,{correct,note});}
 recordStructuredAttempt(studentId:number,conceptId:string,input:AttemptInput):LearnerSnapshot{getConcept(conceptId);const evidence:EvidenceInput={kind:'attempt',value:input.correct?1:0,note:input.note??null,lessonId:input.lessonId??null,problemId:input.problemId??null,reasoning:input.reasoning??null,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null};const evidenceId=this.store.addEvidence(studentId,conceptId,evidence);this.store.recordMastery(studentId,conceptId,input.correct);const findings=mergeDiagnosticCodes(conceptId,input.reasoning,input.misconceptionCodes,input.misconceptionSeverity??1);for(const finding of findings){const m=this.store.upsertMisconception(studentId,conceptId,finding.code,finding.severity,evidenceId);const plan=getInterventionPlan(finding);const first=plan?.problems.find(p=>p.stage==='discrimination');if(plan&&first)this.store.queueIntervention(studentId,m.id,conceptId,plan.prerequisiteConceptId,first.id,'discrimination',plan.strategy);}this.store.saveSession(studentId,'learning',conceptId,0);return this.snapshot(studentId);}
 diagnoseAttempt(conceptId:string,reasoning:string):ReturnType<typeof diagnoseReasoning>{return diagnoseReasoning(conceptId,reasoning);}
 getInterventionQueue(studentId:number):InterventionRecord[]{return this.store.listInterventions(studentId).filter(i=>i.status==='queued'||i.status==='active');}
 nextIntervention(studentId:number):InterventionRecord|undefined{const queue=this.getInterventionQueue(studentId);const selected=selectIntervention(this.store.listMisconceptions(studentId).filter(m=>m.status==='active'),queue);if(!selected)return undefined;const intervention=queue.find(i=>i.id===selected.interventionId);if(intervention?.status==='queued')this.store.activateIntervention(intervention.id);return intervention?this.store.getIntervention(intervention.id):undefined;}
 submitRemediationAttempt(studentId:number,interventionId:number,input:RemediationInput):RemediationResult{const intervention=this.store.getIntervention(interventionId);if(!intervention||intervention.studentId!==studentId)throw new Error('Unknown learner intervention');const problem=getRemediationProblem(intervention.problemId);if(problem.stage!==intervention.stage)throw new Error('Intervention stage does not match remediation problem');if(intervention.status==='queued')this.store.activateIntervention(interventionId);const evidenceId=this.store.addEvidence(studentId,problem.conceptId,{kind:'remediation_attempt',value:input.correct?1:0,problemId:problem.id,reasoning:input.reasoning,note:input.answer,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null});const evaluation=evaluateRemediation(problem,input.reasoning,input.answer,input.correct);const attemptId=this.store.addRemediationAttempt(interventionId,evidenceId,evaluation.verdict,evaluation.checkpointScore);const m=this.store.listMisconceptions(studentId,problem.conceptId).find(x=>x.code===problem.misconceptionCode);if(m)this.store.recordMisconceptionSignal(m.id,evaluation.verdict as RemediationVerdict);if(evaluation.verdict==='repaired'&&intervention.stage==='discrimination'){const plan=getInterventionPlan({code:problem.misconceptionCode});const next=plan?.problems.find(p=>p.stage==='transfer');if(next)this.store.queueIntervention(studentId,intervention.misconceptionId,problem.conceptId,problem.prerequisiteConceptId,next.id,'transfer',plan!.strategy);this.store.completeIntervention(interventionId);}else if(evaluation.verdict==='repaired'&&intervention.stage==='transfer'){this.store.completeIntervention(interventionId);if(m){const state=this.store.getMisconceptionState(m.id);if(state&&state.positiveEvidence>=2&&state.confidence<=30)this.store.markMisconceptionRepaired(studentId,m.id);}this.store.scheduleReview(studentId,problem.conceptId,evaluation.checkpointScore);}if(evaluation.newMisconceptions.length){const all=diagnoseReasoning(problem.conceptId,input.reasoning);for(const code of evaluation.newMisconceptions){const finding=all.find(f=>f.code===code);const plan=finding&&getInterventionPlan(finding);if(finding&&plan){const first=plan.problems.find(p=>p.stage==='discrimination');if(first){const nm=this.store.upsertMisconception(studentId,problem.conceptId,code,finding.severity,evidenceId);this.store.queueIntervention(studentId,nm.id,problem.conceptId,plan.prerequisiteConceptId,first.id,'discrimination',plan.strategy);}}}}return{evaluation,attemptId,snapshot:this.snapshot(studentId)};}
 nextReview(studentId:number):ReviewRecord|undefined{return this.store.listDueReviews(studentId)[0];}
 getReviewProblem(studentId:number):ReviewProblem|undefined{const review=this.nextReview(studentId);return review?getReviewProblemForConcept(review.conceptId):undefined;}
 submitReviewAttempt(studentId:number,input:ReviewInput):ReviewResult{const review=this.nextReview(studentId);if(!review)throw new Error('No review is due for this learner');const problem=getReviewProblemForConcept(review.conceptId);if(!problem)throw new Error(`No review problem is available for concept: ${review.conceptId}`);const evidenceId=this.store.addEvidence(studentId,problem.conceptId,{kind:'review_attempt',value:input.correct?1:0,problemId:problem.id,reasoning:input.reasoning,note:input.answer,confidence:input.confidence??null,hintUsed:input.hintUsed??false,durationSeconds:input.durationSeconds??null});const evaluation=evaluateRemediation(problem,input.reasoning,input.answer,input.correct);const outcome:ReviewResult['outcome']=evaluation.verdict==='repaired'?'retained':evaluation.verdict==='still_present'?'misconception_reopened':evaluation.verdict==='new_misconception'?'new_misconception':'insufficient_evidence';const m=this.store.listMisconceptions(studentId,problem.conceptId).find(x=>x.code===problem.misconceptionCode);if(m)this.store.recordMisconceptionSignal(m.id,evaluation.verdict as RemediationVerdict);this.store.recordMastery(studentId,problem.conceptId,input.correct);const attemptId=this.store.addReviewAttempt(studentId,problem.conceptId,problem.id,evidenceId,outcome,evaluation.checkpointScore);if(outcome==='retained'){if(m){const state=this.store.getMisconceptionState(m.id);if(state&&state.confidence<=30&&state.positiveEvidence>=2)this.store.markMisconceptionRepaired(studentId,m.id);}this.store.scheduleReview(studentId,problem.conceptId,evaluation.checkpointScore);}else{this.store.scheduleReview(studentId,problem.conceptId,Math.min(evaluation.checkpointScore,0.5));const findings=mergeDiagnosticCodes(problem.conceptId,input.reasoning);for(const finding of findings){const plan=getInterventionPlan(finding);if(plan){const target=this.store.listMisconceptions(studentId,problem.conceptId).find(x=>x.code===finding.code)??this.store.upsertMisconception(studentId,problem.conceptId,finding.code,finding.severity,evidenceId);const first=plan.problems.find(p=>p.stage==='discrimination');if(first)this.store.queueIntervention(studentId,target.id,problem.conceptId,plan.prerequisiteConceptId,first.id,'discrimination',plan.strategy);}}}return{outcome,problemId:problem.id,attemptId,checkpointScore:evaluation.checkpointScore,snapshot:this.snapshot(studentId)};}
 saveResume(studentId:number,lessonId:string|null,problemId:string|null,step:number,state:unknown=null):LearnerSnapshot{this.store.saveResume(studentId,lessonId,problemId,step,state);return this.snapshot(studentId);}
 resolveMisconception(studentId:number,misconceptionId:number):LearnerSnapshot{this.store.resolveMisconception(studentId,misconceptionId);return this.snapshot(studentId);}
 placeByDemonstratedMastery(studentId:number,scores:Record<string,number>):LearnerSnapshot{for(const[conceptId,score]of Object.entries(scores)){getConcept(conceptId);this.store.setMastery(studentId,conceptId,score);this.store.addEvidence(studentId,conceptId,'placement',score,'Demonstrated ability placement');}this.store.saveSession(studentId,'learning',null,0);return this.snapshot(studentId);}
}
