import { chooseNextPhysicsConcept, CURRICULUM, getConcept, missingRequirements } from './curriculum.js';
import { DiagnosticEngine } from './diagnostic.js';
import { getProblem, isAnswerCorrect, problemsForConcept, PhysicsProblem } from './problems.js';
import { LearningStore, MisconceptionRecord, ProblemAttemptRecord, ReviewRecord, ResumeState } from './store.js';

export type LearningStatus = 'new' | 'diagnostic' | 'learning';
export type JourneyStatus = 'locked' | 'available' | 'learning' | 'mastered';
export interface JourneyNode { id:string; name:string; domain:string; status:JourneyStatus; mastery:number; prerequisites:string[]; mathDependencies:string[]; }
export interface RemediationPlan { misconceptionId:number|null; sourceConcept:string; targetConcept:string; reason:'misconception'|'prerequisite'; retryRequired:true; }
export interface LearnerSnapshot { studentId:number; status:LearningStatus; currentConcept:string|null; nextConcept:string|null; mastery:Record<string,number>; missingRequirements:string[]; openMisconceptions:number; resume:ResumeState|undefined; dueReviews:ReviewRecord[]; journey:JourneyNode[]; }
export interface ProblemSubmission { problemId:string; answer:string; reasoning:string; confidence?:number|null; }

export class LearningEngine {
  constructor(private readonly store: LearningStore) {}
  start(studentId:number): LearnerSnapshot { if (!this.store.getSession(studentId)) this.store.saveSession(studentId,'diagnostic',null,0); return this.snapshot(studentId); }
  journey(studentId:number): JourneyNode[] { const mastery=this.store.getMastery(studentId); return CURRICULUM.map(c => { const score=mastery[c.id]??0; const req=missingRequirements(mastery,c.id); const status:JourneyStatus=score>=100?'mastered':req.length?'locked':score>0?'learning':'available'; return {id:c.id,name:c.name,domain:c.domain,status,mastery:score,prerequisites:[...c.prerequisites],mathDependencies:[...c.mathDependencies]}; }); }
  snapshot(studentId:number): LearnerSnapshot { const session=this.store.getSession(studentId); const mastery=this.store.getMastery(studentId); const next=chooseNextPhysicsConcept(mastery); return {studentId,status:(session?.status??'new') as LearningStatus,currentConcept:session?.currentConcept??null,nextConcept:next?.id??null,mastery,missingRequirements:next?missingRequirements(mastery,next.id):[],openMisconceptions:this.store.listOpenMisconceptions(studentId).length,resume:this.store.getResume(studentId),dueReviews:this.store.getDueReviews(studentId),journey:this.journey(studentId)}; }
  diagnostic(studentId:number, observations: import('./diagnostic.js').DiagnosticObservation[]) { return new DiagnosticEngine(this.store).evaluate(studentId,observations); }
  setCurrent(studentId:number, conceptId:string): void { getConcept(conceptId); const missing=missingRequirements(this.store.getMastery(studentId),conceptId); if(missing.length) throw new Error(`Cannot start ${conceptId}; requirements not yet demonstrated: ${missing.join(', ')}`); this.store.saveSession(studentId,'learning',conceptId,0); }
  saveResume(studentId:number, lessonId:string, problemId:string|null, step:number): void { this.store.saveResume(studentId,lessonId,problemId,step); }
  problems(studentId:number, conceptId:string): PhysicsProblem[] { getConcept(conceptId); const missing=missingRequirements(this.store.getMastery(studentId),conceptId); if(missing.length) throw new Error(`Cannot load problems for ${conceptId}; requirements not yet demonstrated: ${missing.join(', ')}`); return problemsForConcept(conceptId); }
  problem(studentId:number, problemId:string): PhysicsProblem { const problem=getProblem(problemId); const missing=missingRequirements(this.store.getMastery(studentId),problem.conceptId); if(missing.length) throw new Error(`Cannot load problem ${problemId}; requirements not yet demonstrated: ${missing.join(', ')}`); return problem; }
  submitProblem(studentId:number, submission:ProblemSubmission): ProblemAttemptRecord { const problem=this.problem(studentId,submission.problemId); if(!submission.reasoning.trim()) throw new Error('Reasoning is required for a problem attempt'); const correct=isAnswerCorrect(problem,submission.answer); const confidence=submission.confidence ?? null; const attempt=this.store.recordProblemAttempt(studentId,problem.id,problem.conceptId,submission.answer,correct,submission.reasoning,confidence); this.store.addEvidence(studentId,problem.conceptId,'problem',correct?100:0,submission.reasoning); this.store.recordMastery(studentId,problem.conceptId,correct); this.store.scheduleReview(studentId,problem.conceptId,correct); this.store.saveResume(studentId,`${problem.conceptId}-problems`,problem.id,0); this.store.saveSession(studentId,'learning',problem.conceptId,0); return attempt; }
  recordAttempt(studentId:number, conceptId:string, correct:boolean, note=''): LearnerSnapshot { getConcept(conceptId); this.store.recordMastery(studentId,conceptId,correct); this.store.addEvidence(studentId,conceptId,'attempt',correct?1:0,note); this.store.scheduleReview(studentId,conceptId,correct); this.store.saveSession(studentId,'learning',conceptId,0); return this.snapshot(studentId); }
  recordMisconception(studentId:number, conceptId:string, code:string, note:string): MisconceptionRecord { getConcept(conceptId); return this.store.addMisconception(studentId,conceptId,code,note); }
  remediation(studentId:number, conceptId:string): RemediationPlan|null { getConcept(conceptId); const mastery=this.store.getMastery(studentId); const misconception=this.store.listOpenMisconceptions(studentId,conceptId)[0]; const target=missingRequirements(mastery,conceptId)[0]; if(misconception) return {misconceptionId:misconception.id,sourceConcept:conceptId,targetConcept:target??conceptId,reason:'misconception',retryRequired:true}; if(target) return {misconceptionId:null,sourceConcept:conceptId,targetConcept:target,reason:'prerequisite',retryRequired:true}; return null; }
  retryRemediation(studentId:number, misconceptionId:number, targetConcept:string, correct:boolean, note=''): LearnerSnapshot { const misconception=this.store.getMisconception(misconceptionId); if(!misconception || misconception.studentId!==studentId || misconception.status!=='open') throw new Error('Open misconception not found for learner'); getConcept(targetConcept); this.store.addEvidence(studentId,targetConcept,'problem',correct?100:0,`Remediation retry: ${note}`); this.store.recordMastery(studentId,targetConcept,correct); this.store.scheduleReview(studentId,targetConcept,correct); if(correct) this.store.resolveMisconception(misconceptionId); return this.snapshot(studentId); }
  listOpenMisconceptions(studentId:number, conceptId?:string): MisconceptionRecord[] { return this.store.listOpenMisconceptions(studentId,conceptId); }
  resolveMisconception(id:number): void { this.store.resolveMisconception(id); }
  placeByDemonstratedMastery(studentId:number, scores:Record<string,number>): LearnerSnapshot { for(const [conceptId,score] of Object.entries(scores)){getConcept(conceptId);this.store.setMastery(studentId,conceptId,score);this.store.addEvidence(studentId,conceptId,'placement',score,'Demonstrated ability placement');} this.store.saveSession(studentId,'learning',null,0); return this.snapshot(studentId); }
}
