import type { ProblemAnswerSpec } from './problem-answer-spec.js';

export interface PracticeCheckpoint { id:string; label:string; patterns:readonly RegExp[]; }
export interface PracticeProblem {
  id:string;
  conceptId:string;
  title:string;
  prompt:string;
  givens:readonly string[];
  checkpoints:readonly PracticeCheckpoint[];
  answerSpec:ProblemAnswerSpec;
}

export const PRACTICE_PROBLEMS:Readonly<Record<string,PracticeProblem>>={
  'forces-1':{id:'forces-1',conceptId:'forces',title:'Net force and motion',prompt:'A 2 kg cart moves east at a constant 5 m/s on a level, nearly frictionless track. What is its net horizontal force? Explain what a force would change.',givens:['m = 2 kg','constant velocity = 5 m/s east','negligible horizontal friction'],checkpoints:[{id:'acceleration',label:'Acceleration',patterns:[/constant velocity.*(?:zero|0).*acceleration/i,/acceleration.*(?:zero|0).*constant velocity/i]},{id:'net-force',label:'Net force',patterns:[/zero.*net force/i,/net force.*(?:zero|0)/i,/f\s*[_ ]?net\s*=\s*m\s*a/i]},{id:'causation',label:'Causal model',patterns:[/(?:force|net force).*changes?.*(?:velocity|motion).*acceleration/i,/acceleration.*changes?.*velocity/i]}],answerSpec:{criteria:[{id:'net-force',kind:'numeric',expected:0,unit:'N'},{id:'causal-model',kind:'concept',patterns:[/constant velocity.*(?:does not|doesn.?t).*force/i,/(?:force|net force).*changes?.*velocity.*acceleration/i]}]}},
  'energy-1':{id:'energy-1',conceptId:'energy',title:'Force versus work',prompt:'A 5 N horizontal force pushes a box 4 m in the direction of the force. Calculate the work done and explain why work is not the same physical quantity as force.',givens:['F = 5 N','d = 4 m','force parallel to displacement'],checkpoints:[{id:'equation',label:'Work equation',patterns:[/w\s*=\s*f\s*d/i,/5\s*(?:n|newtons?).*4\s*m/i]},{id:'result',label:'Work result',patterns:[/20\s*(?:j|joules?)/i]},{id:'distinction',label:'Quantity distinction',patterns:[/force.*(?:different|not the same).*work/i,/work.*(?:different|not the same).*force/i,/n.*j.*different/i]}],answerSpec:{criteria:[{id:'work',kind:'numeric',expected:20,unit:'J'},{id:'quantity-distinction',kind:'concept',patterns:[/force.*(?:different|not the same).*work/i,/work.*(?:different|not the same).*force/i]}]}},
  'temperature-1':{id:'temperature-1',conceptId:'temperature_heat',title:'Temperature and heat',prompt:'Two cups contain equal masses of water. Cup A is at 20 °C and Cup B is at 60 °C. Explain whether temperature is an amount of heat, and what heat means if the cups are brought into contact.',givens:['equal masses of water','20 °C and 60 °C'],checkpoints:[{id:'temperature',label:'Thermal state',patterns:[/temperature.*(?:thermal state|state)/i]},{id:'heat',label:'Energy transfer',patterns:[/(?:heat|energy).*transfer/i,/temperature difference.*transfer/i]},{id:'distinction',label:'Concept distinction',patterns:[/temperature.*not.*(?:heat|amount)/i,/heat.*not.*(?:a substance|stored)/i]}],answerSpec:{criteria:[{id:'temperature-distinction',kind:'concept',patterns:[/temperature.*not.*(?:heat|amount)/i,/not.*(?:heat|amount).*temperature/i]},{id:'heat-transfer',kind:'concept',patterns:[/(?:heat|energy).*transfer/i]}]}},
  'vectors-1':{id:'vectors-1',conceptId:'forces',title:'Vectors in one dimension',prompt:'A 10 N force acts east while a 6 N force acts west. Find the net force and explain why the directions cannot be ignored.',givens:['10 N east','6 N west'],checkpoints:[{id:'direction',label:'Direction',patterns:[/opposite directions/i,/west.*negative/i,/signed.*(?:force|vector)/i]},{id:'result',label:'Net force',patterns:[/4\s*(?:n|newtons?).*east/i,/net force.*4.*east/i]},{id:'vector',label:'Vector treatment',patterns:[/direction.*matter/i,/vector/i]}],answerSpec:{criteria:[{id:'net-force',kind:'numeric',expected:4,unit:'N',direction:'east'},{id:'direction',kind:'concept',patterns:[/opposite directions/i,/west.*negative/i,/direction.*matter/i]}]}},
  'ratio-1':{id:'ratio-1',conceptId:'fractions',title:'Multiplicative scaling',prompt:'A model car travels 3 km for every 2 minutes at constant speed. How far will it travel in 6 minutes? Explain the scaling relationship.',givens:['3 km per 2 min','time = 6 min'],checkpoints:[{id:'scale',label:'Scale factor',patterns:[/multiply.*3/i,/scale.*3/i,/three.*times/i]},{id:'result',label:'Distance',patterns:[/9\s*km/i]},{id:'relationship',label:'Proportional relationship',patterns:[/multiplicative/i,/same.*scale factor/i,/ratio.*scale/i]}],answerSpec:{criteria:[{id:'distance',kind:'numeric',expected:9,unit:'km'},{id:'scaling',kind:'concept',patterns:[/multiplicative/i,/same.*scale factor/i,/ratio.*scale/i]}]}}
};

export function getPracticeProblem(problemId:string):PracticeProblem{const problem=PRACTICE_PROBLEMS[problemId];if(!problem)throw new Error(`Unknown practice problem: ${problemId}`);return problem;}
export function getPracticeProblemForConcept(conceptId:string):PracticeProblem|undefined{return Object.values(PRACTICE_PROBLEMS).find(p=>p.conceptId===conceptId);}
