import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

export interface MasteryRecord { studentId:number; conceptId:string; score:number; attempts:number; correct:number; updatedAt:string; }
export interface EvidenceInput { kind:string; value?:number|null; note?:string; lessonId?:string|null; problemId?:string|null; reasoning?:string|null; confidence?:number|null; hintUsed?:boolean; durationSeconds?:number|null; }
export interface MisconceptionRecord { id:number; studentId:number; conceptId:string; code:string; severity:number; status:'active'|'resolved'; occurrences:number; lastEvidenceId:number|null; updatedAt:string; }
export interface MisconceptionState { misconceptionId:number; confidence:number; positiveEvidence:number; negativeEvidence:number; lastVerdict:string|null; updatedAt:string; }
export interface InterventionRecord { id:number; studentId:number; misconceptionId:number; conceptId:string; prerequisiteConceptId:string; problemId:string; stage:'discrimination'|'transfer'; strategy:string; status:'queued'|'active'|'completed'|'blocked'; createdAt:string; updatedAt:string; }
export interface RemediationAttempt { id:number; interventionId:number; evidenceId:number; verdict:string; checkpointScore:number; createdAt:string; }
export interface ReviewRecord { studentId:number; conceptId:string; dueAt:string; intervalDays:number; streak:number; lastScore:number; updatedAt:string; }
export interface ReviewAttempt { id:number; studentId:number; conceptId:string; problemId:string; evidenceId:number; outcome:string; checkpointScore:number; createdAt:string; }
export interface ResumeState { lessonId:string|null; problemId:string|null; step:number; stateJson:string|null; updatedAt:string; }

export class LearningStore {
  readonly db: DatabaseSync;
  constructor(path = process.env.VITA_DB_PATH ?? './data/vita.sqlite') {
    if (path !== ':memory:') mkdirSync(dirname(path), { recursive:true });
    this.db = new DatabaseSync(path);
    this.db.exec('PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;');
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS students (id INTEGER PRIMARY KEY AUTOINCREMENT, nickname TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS mastery (student_id INTEGER NOT NULL, concept_id TEXT NOT NULL, score REAL NOT NULL DEFAULT 0, attempts INTEGER NOT NULL DEFAULT 0, correct INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, PRIMARY KEY(student_id, concept_id), FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS learner_sessions (student_id INTEGER PRIMARY KEY, status TEXT NOT NULL, current_concept TEXT, diagnostic_index INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS evidence (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, concept_id TEXT NOT NULL, kind TEXT NOT NULL, value REAL, note TEXT, lesson_id TEXT, problem_id TEXT, reasoning TEXT, confidence REAL, hint_used INTEGER NOT NULL DEFAULT 0, duration_seconds INTEGER, created_at TEXT NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS misconceptions (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, concept_id TEXT NOT NULL, code TEXT NOT NULL, severity INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'active', occurrences INTEGER NOT NULL DEFAULT 1, last_evidence_id INTEGER, updated_at TEXT NOT NULL, UNIQUE(student_id, concept_id, code), FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE, FOREIGN KEY(last_evidence_id) REFERENCES evidence(id) ON DELETE SET NULL);
      CREATE TABLE IF NOT EXISTS misconception_state (misconception_id INTEGER PRIMARY KEY, confidence INTEGER NOT NULL DEFAULT 0, positive_evidence INTEGER NOT NULL DEFAULT 0, negative_evidence INTEGER NOT NULL DEFAULT 0, last_verdict TEXT, updated_at TEXT NOT NULL, FOREIGN KEY(misconception_id) REFERENCES misconceptions(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS interventions (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, misconception_id INTEGER NOT NULL, concept_id TEXT NOT NULL, prerequisite_concept_id TEXT NOT NULL, problem_id TEXT NOT NULL, stage TEXT NOT NULL, strategy TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE, FOREIGN KEY(misconception_id) REFERENCES misconceptions(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS remediation_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, intervention_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, verdict TEXT NOT NULL, checkpoint_score REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL, FOREIGN KEY(intervention_id) REFERENCES interventions(id) ON DELETE CASCADE, FOREIGN KEY(evidence_id) REFERENCES evidence(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS concept_reviews (student_id INTEGER NOT NULL, concept_id TEXT NOT NULL, due_at TEXT NOT NULL, interval_days INTEGER NOT NULL DEFAULT 1, streak INTEGER NOT NULL DEFAULT 0, last_score REAL NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, PRIMARY KEY(student_id, concept_id), FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS review_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, concept_id TEXT NOT NULL, problem_id TEXT NOT NULL, evidence_id INTEGER NOT NULL, outcome TEXT NOT NULL, checkpoint_score REAL NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE, FOREIGN KEY(evidence_id) REFERENCES evidence(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS resume_state (student_id INTEGER PRIMARY KEY, lesson_id TEXT, problem_id TEXT, step INTEGER NOT NULL DEFAULT 0, state_json TEXT, updated_at TEXT NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
    `);
  }
  close():void { this.db.close(); }
  ensureStudent(nickname:string):number { const x=this.db.prepare('SELECT id FROM students WHERE nickname=?').get(nickname) as {id:number}|undefined; if(x) return x.id; const r=this.db.prepare('INSERT INTO students(nickname,created_at) VALUES(?,?)').run(nickname,new Date().toISOString()); return Number(r.lastInsertRowid); }
  getMastery(studentId:number):Record<string,number> { const rows=this.db.prepare('SELECT concept_id,score FROM mastery WHERE student_id=?').all(studentId) as Array<{concept_id:string;score:number}>; return Object.fromEntries(rows.map(r=>[r.concept_id,r.score])); }
  recordMastery(studentId:number,conceptId:string,correct:boolean):MasteryRecord { const now=new Date().toISOString(); const c=this.db.prepare('SELECT score,attempts,correct FROM mastery WHERE student_id=? AND concept_id=?').get(studentId,conceptId) as {score:number;attempts:number;correct:number}|undefined; const attempts=(c?.attempts??0)+1; const correctCount=(c?.correct??0)+(correct?1:0); const score=Math.round(correctCount/attempts*1000)/10; this.db.prepare('INSERT INTO mastery(student_id,concept_id,score,attempts,correct,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(student_id,concept_id) DO UPDATE SET score=excluded.score,attempts=excluded.attempts,correct=excluded.correct,updated_at=excluded.updated_at').run(studentId,conceptId,score,attempts,correctCount,now); return {studentId,conceptId,score,attempts,correct:correctCount,updatedAt:now}; }
  setMastery(studentId:number,conceptId:string,score:number):void { if(!Number.isFinite(score)||score<0||score>100) throw new Error('Mastery score must be between 0 and 100'); const now=new Date().toISOString(); this.db.prepare('INSERT INTO mastery(student_id,concept_id,score,updated_at) VALUES(?,?,?,?) ON CONFLICT(student_id,concept_id) DO UPDATE SET score=excluded.score,updated_at=excluded.updated_at').run(studentId,conceptId,score,now); }
  saveSession(studentId:number,status:string,currentConcept:string|null,diagnosticIndex:number):void { this.db.prepare('INSERT INTO learner_sessions(student_id,status,current_concept,diagnostic_index,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET status=excluded.status,current_concept=excluded.current_concept,diagnostic_index=excluded.diagnostic_index,updated_at=excluded.updated_at').run(studentId,status,currentConcept,diagnosticIndex,new Date().toISOString()); }
  getSession(studentId:number):{status:string;currentConcept:string|null;diagnosticIndex:number}|undefined { const r=this.db.prepare('SELECT status,current_concept,diagnostic_index FROM learner_sessions WHERE student_id=?').get(studentId) as {status:string;current_concept:string|null;diagnosticIndex:number}|undefined; return r?{status:r.status,currentConcept:r.current_concept,diagnosticIndex:r.diagnostic_index}:undefined; }
  addEvidence(studentId:number,conceptId:string,input:string|EvidenceInput,value:number|null=null,note=''):number { const e:EvidenceInput=typeof input==='string'?{kind:input,value,note}:input; const r=this.db.prepare('INSERT INTO evidence(student_id,concept_id,kind,value,note,lesson_id,problem_id,reasoning,confidence,hint_used,duration_seconds,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(studentId,conceptId,e.kind,e.value??null,e.note??null,e.lessonId??null,e.problemId??null,e.reasoning??null,e.confidence??null,e.hintUsed?1:0,e.durationSeconds??null,new Date().toISOString()); return Number(r.lastInsertRowid); }
  upsertMisconception(studentId:number,conceptId:string,code:string,severity:number,evidenceId:number|null):MisconceptionRecord { if(!Number.isInteger(severity)||severity<1||severity>5) throw new Error('Misconception severity must be between 1 and 5'); const now=new Date().toISOString(); this.db.prepare("INSERT INTO misconceptions(student_id,concept_id,code,severity,status,occurrences,last_evidence_id,updated_at) VALUES(?,?,?,?, 'active',1,?,?) ON CONFLICT(student_id,concept_id,code) DO UPDATE SET severity=excluded.severity,status='active',occurrences=misconceptions.occurrences+1,last_evidence_id=excluded.last_evidence_id,updated_at=excluded.updated_at").run(studentId,conceptId,code,severity,evidenceId,now); const r=this.db.prepare('SELECT id,student_id,concept_id,code,severity,status,occurrences,last_evidence_id,updated_at FROM misconceptions WHERE student_id=? AND concept_id=? AND code=?').get(studentId,conceptId,code) as MisconceptionRecord; this.db.prepare('INSERT INTO misconception_state(misconception_id,confidence,positive_evidence,negative_evidence,last_verdict,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(misconception_id) DO UPDATE SET confidence=MIN(100,misconception_state.confidence+15),negative_evidence=misconception_state.negative_evidence+1,last_verdict=excluded.last_verdict,updated_at=excluded.updated_at').run(r.id,Math.min(100,severity*20),0,1,'still_present',now); return r; }
  listMisconceptions(studentId:number,conceptId?:string):MisconceptionRecord[] { const rows=conceptId?this.db.prepare('SELECT id,student_id,concept_id,code,severity,status,occurrences,last_evidence_id,updated_at FROM misconceptions WHERE student_id=? AND concept_id=? ORDER BY severity DESC,updated_at DESC').all(studentId,conceptId):this.db.prepare('SELECT id,student_id,concept_id,code,severity,status,occurrences,last_evidence_id,updated_at FROM misconceptions WHERE student_id=? ORDER BY severity DESC,updated_at DESC').all(studentId); return rows as MisconceptionRecord[]; }
  getMisconceptionState(misconceptionId:number):MisconceptionState|undefined { return this.db.prepare('SELECT misconception_id,confidence,positive_evidence,negative_evidence,last_verdict,updated_at FROM misconception_state WHERE misconception_id=?').get(misconceptionId) as MisconceptionState|undefined; }
  recordMisconceptionSignal(misconceptionId:number,verdict:'repaired'|'still_present'|'new_misconception'|'insufficient_evidence'):MisconceptionState { const now=new Date().toISOString(); const negative=verdict==='still_present'||verdict==='new_misconception'; const delta=negative?15:verdict==='repaired'?-30:0; this.db.prepare('INSERT INTO misconception_state(misconception_id,confidence,positive_evidence,negative_evidence,last_verdict,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(misconception_id) DO UPDATE SET confidence=MAX(0,MIN(100,misconception_state.confidence+?)),positive_evidence=misconception_state.positive_evidence+?,negative_evidence=misconception_state.negative_evidence+?,last_verdict=?,updated_at=?').run(misconceptionId,Math.max(0,delta),verdict==='repaired'?1:0,negative?1:0,verdict,now,delta,verdict==='repaired'?1:0,negative?1:0,verdict,now); if(negative)this.db.prepare("UPDATE misconceptions SET status='active',updated_at=? WHERE id=?").run(now,misconceptionId); return this.getMisconceptionState(misconceptionId)!; }
  markMisconceptionRepaired(studentId:number,misconceptionId:number):void { const state=this.getMisconceptionState(misconceptionId); if(!state||state.positiveEvidence<2||state.confidence>30) throw new Error('Misconception cannot be resolved without repeated positive repair evidence'); this.db.prepare("UPDATE misconceptions SET status='resolved',updated_at=? WHERE id=? AND student_id=?").run(new Date().toISOString(),misconceptionId,studentId); }
  queueIntervention(studentId:number,misconceptionId:number,conceptId:string,prerequisiteConceptId:string,problemId:string,stage:'discrimination'|'transfer',strategy:string):InterventionRecord { const now=new Date().toISOString(); const existing=this.db.prepare("SELECT id FROM interventions WHERE student_id=? AND misconception_id=? AND stage=? AND status IN ('queued','active')").get(studentId,misconceptionId,stage) as {id:number}|undefined; if(existing) return this.getIntervention(existing.id)!; const r=this.db.prepare('INSERT INTO interventions(student_id,misconception_id,concept_id,prerequisite_concept_id,problem_id,stage,strategy,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,\'queued\',?,?)').run(studentId,misconceptionId,conceptId,prerequisiteConceptId,problemId,stage,strategy,now,now); return this.getIntervention(Number(r.lastInsertRowid))!; }
  getIntervention(id:number):InterventionRecord|undefined { const r=this.db.prepare('SELECT id,student_id,misconception_id,concept_id,prerequisite_concept_id,problem_id,stage,strategy,status,created_at,updated_at FROM interventions WHERE id=?').get(id) as any; return r?{id:r.id,studentId:r.student_id,misconceptionId:r.misconception_id,conceptId:r.concept_id,prerequisiteConceptId:r.prerequisite_concept_id,problemId:r.problem_id,stage:r.stage,status:r.status,strategy:r.strategy,createdAt:r.created_at,updatedAt:r.updated_at}:undefined; }
  listInterventions(studentId:number,status?:string):InterventionRecord[] { const rows=status?this.db.prepare('SELECT id FROM interventions WHERE student_id=? AND status=? ORDER BY id').all(studentId,status):this.db.prepare('SELECT id FROM interventions WHERE student_id=? ORDER BY CASE status WHEN \'active\' THEN 0 WHEN \'queued\' THEN 1 ELSE 2 END,id').all(studentId); return (rows as Array<{id:number}>).map(r=>this.getIntervention(r.id)!); }
  activateIntervention(id:number):void { this.db.prepare("UPDATE interventions SET status='active',updated_at=? WHERE id=? AND status='queued'").run(new Date().toISOString(),id); }
  completeIntervention(id:number):void { this.db.prepare("UPDATE interventions SET status='completed',updated_at=? WHERE id=?").run(new Date().toISOString(),id); }
  addRemediationAttempt(interventionId:number,evidenceId:number,verdict:string,checkpointScore:number):number { if(!Number.isFinite(checkpointScore)||checkpointScore<0||checkpointScore>1) throw new Error('Checkpoint score must be between 0 and 1'); const r=this.db.prepare('INSERT INTO remediation_attempts(intervention_id,evidence_id,verdict,checkpoint_score,created_at) VALUES(?,?,?,?,?)').run(interventionId,evidenceId,verdict,checkpointScore,new Date().toISOString()); return Number(r.lastInsertRowid); }
  scheduleReview(studentId:number,conceptId:string,score:number,referenceTime=new Date()):ReviewRecord { if(!Number.isFinite(score)||score<0||score>1) throw new Error('Review score must be between 0 and 1'); const old=this.db.prepare('SELECT interval_days,streak FROM concept_reviews WHERE student_id=? AND concept_id=?').get(studentId,conceptId) as {interval_days:number;streak:number}|undefined; const strong=score>=0.8; const streak=strong?(old?.streak??0)+1:0; const intervalDays=strong?Math.min(90,Math.max(1,(old?.interval_days??1)*(streak>=3?3:2))):1; const due=new Date(referenceTime.getTime()+intervalDays*86400000).toISOString(); const r={studentId,conceptId,dueAt:due,intervalDays,streak,lastScore:score,updatedAt:referenceTime.toISOString()}; this.db.prepare('INSERT INTO concept_reviews(student_id,concept_id,due_at,interval_days,streak,last_score,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(student_id,concept_id) DO UPDATE SET due_at=excluded.due_at,interval_days=excluded.interval_days,streak=excluded.streak,last_score=excluded.last_score,updated_at=excluded.updated_at').run(studentId,conceptId,due,intervalDays,streak,score,r.updatedAt); return r; }
  listDueReviews(studentId:number,now=new Date().toISOString()):ReviewRecord[] { const rows=this.db.prepare('SELECT student_id,concept_id,due_at,interval_days,streak,last_score,updated_at FROM concept_reviews WHERE student_id=? AND due_at<=? ORDER BY due_at').all(studentId,now) as any[]; return rows.map(r=>({studentId:r.student_id,conceptId:r.concept_id,dueAt:r.due_at,intervalDays:r.interval_days,streak:r.streak,lastScore:r.last_score,updatedAt:r.updated_at})); }
  addReviewAttempt(studentId:number,conceptId:string,problemId:string,evidenceId:number,outcome:string,checkpointScore:number):number { if(!Number.isFinite(checkpointScore)||checkpointScore<0||checkpointScore>1) throw new Error('Checkpoint score must be between 0 and 1'); const r=this.db.prepare('INSERT INTO review_attempts(student_id,concept_id,problem_id,evidence_id,outcome,checkpoint_score,created_at) VALUES(?,?,?,?,?,?,?)').run(studentId,conceptId,problemId,evidenceId,outcome,checkpointScore,new Date().toISOString()); return Number(r.lastInsertRowid); }
  resolveMisconception(studentId:number,misconceptionId:number):void { this.markMisconceptionRepaired(studentId,misconceptionId); }
  saveResume(studentId:number,lessonId:string|null,problemId:string|null,step:number,state:unknown=null):void { if(!Number.isInteger(step)||step<0) throw new Error('Resume step must be a non-negative integer'); const stateJson=state===null?null:JSON.stringify(state); this.db.prepare('INSERT INTO resume_state(student_id,lesson_id,problem_id,step,state_json,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET lesson_id=excluded.lesson_id,problem_id=excluded.problem_id,step=excluded.step,state_json=excluded.state_json,updated_at=excluded.updated_at').run(studentId,lessonId,problemId,step,stateJson,new Date().toISOString()); }
  getResume(studentId:number):ResumeState|undefined { const r=this.db.prepare('SELECT lesson_id,problem_id,step,state_json,updated_at FROM resume_state WHERE student_id=?').get(studentId) as {lesson_id:string|null;problem_id:string|null;step:number;state_json:string|null;updated_at:string}|undefined; return r?{lessonId:r.lesson_id,problemId:r.problem_id,step:r.step,stateJson:r.state_json,updatedAt:r.updated_at}:undefined; }
}
