import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { ReasoningSignal } from './reasoning.js';
import { migrateSqlite } from './sqlite-migrations.js';
import type { EvidenceRecord } from './learning-repository.js';

export interface MasteryRecord { studentId:number; conceptId:string; score:number; attempts:number; correct:number; updatedAt:string; }
export interface MisconceptionRecord { id:number; studentId:number; conceptId:string; code:string; note:string; status:'open'|'resolved'; createdAt:string; resolvedAt:string|null; }
export interface ResumeState { lessonId:string; problemId:string|null; step:number; updatedAt:string; }
export interface ReviewRecord { conceptId:string; dueAt:string; intervalDays:number; repetitions:number; }
export interface ProblemAttemptRecord { id:number; studentId:number; problemId:string; conceptId:string; answer:string; correct:boolean; reasoning:string; confidence:number|null; reasoningSignals:ReasoningSignal[]; misconceptionCodes:string[]; createdAt:string; }

export class LearningStore {
  readonly db:DatabaseSync;
  constructor(path=process.env.VITA_DB_PATH??'./data/vita.sqlite') { if(path!==':memory:') mkdirSync(dirname(path),{recursive:true}); this.db=new DatabaseSync(path); this.db.exec('PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;'); this.db.exec(`
CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT,nickname TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mastery(student_id INTEGER NOT NULL,concept_id TEXT NOT NULL,score REAL NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,correct INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(student_id,concept_id),FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS learner_sessions(student_id INTEGER PRIMARY KEY,status TEXT NOT NULL,current_concept TEXT,diagnostic_index INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS evidence(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,concept_id TEXT NOT NULL,kind TEXT NOT NULL,value REAL,note TEXT,created_at TEXT NOT NULL,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS misconceptions(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,concept_id TEXT NOT NULL,code TEXT NOT NULL,note TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL,resolved_at TEXT,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS resume_state(student_id INTEGER PRIMARY KEY,lesson_id TEXT NOT NULL,problem_id TEXT,step INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS reviews(student_id INTEGER NOT NULL,concept_id TEXT NOT NULL,due_at TEXT NOT NULL,interval_days INTEGER NOT NULL DEFAULT 1,repetitions INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(student_id,concept_id),FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS problem_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,problem_id TEXT NOT NULL,concept_id TEXT NOT NULL,answer TEXT NOT NULL,correct INTEGER NOT NULL,reasoning TEXT NOT NULL,confidence REAL,reasoning_signals TEXT NOT NULL DEFAULT '[]',misconception_codes TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL,FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
`); migrateSqlite(this.db); }
  close():void { this.db.close(); }
  transaction<T>(work:()=>T):T { this.db.exec('BEGIN IMMEDIATE'); try { const result=work(); this.db.exec('COMMIT'); return result; } catch(error) { this.db.exec('ROLLBACK'); throw error; } }
  ensureStudent(nickname:string):number { const existing=this.db.prepare('SELECT id FROM students WHERE nickname=?').get(nickname) as {id:number}|undefined; if(existing)return existing.id; const result=this.db.prepare('INSERT INTO students(nickname,created_at) VALUES(?,?)').run(nickname,new Date().toISOString()); return Number(result.lastInsertRowid); }
  getMastery(studentId:number):Record<string,number> { const rows=this.db.prepare('SELECT concept_id,score FROM mastery WHERE student_id=?').all(studentId) as Array<{concept_id:string;score:number}>; return Object.fromEntries(rows.map(r=>[r.concept_id,r.score])); }
  recordMastery(studentId:number,conceptId:string,correct:boolean):MasteryRecord { const now=new Date().toISOString(); const current=this.db.prepare('SELECT score,attempts,correct FROM mastery WHERE student_id=? AND concept_id=?').get(studentId,conceptId) as {score:number;attempts:number;correct:number}|undefined; const attempts=(current?.attempts??0)+1; const correctCount=(current?.correct??0)+(correct?1:0); const score=Math.round((correctCount/attempts)*1000)/10; this.db.prepare(`INSERT INTO mastery(student_id,concept_id,score,attempts,correct,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(student_id,concept_id) DO UPDATE SET score=excluded.score,attempts=excluded.attempts,correct=excluded.correct,updated_at=excluded.updated_at`).run(studentId,conceptId,score,attempts,correctCount,now); return {studentId,conceptId,score,attempts,correct:correctCount,updatedAt:now}; }
  setMastery(studentId:number,conceptId:string,score:number):void { if(!Number.isFinite(score)||score<0||score>100)throw new Error('Mastery score must be between 0 and 100'); const now=new Date().toISOString(); this.db.prepare(`INSERT INTO mastery(student_id,concept_id,score,updated_at) VALUES(?,?,?,?) ON CONFLICT(student_id,concept_id) DO UPDATE SET score=excluded.score,updated_at=excluded.updated_at`).run(studentId,conceptId,score,now); }
  saveSession(studentId:number,status:string,currentConcept:string|null,diagnosticIndex:number):void { this.db.prepare(`INSERT INTO learner_sessions(student_id,status,current_concept,diagnostic_index,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET status=excluded.status,current_concept=excluded.current_concept,diagnostic_index=excluded.diagnostic_index,updated_at=excluded.updated_at`).run(studentId,status,currentConcept,diagnosticIndex,new Date().toISOString()); }
  getSession(studentId:number):{status:string;currentConcept:string|null;diagnosticIndex:number}|undefined { const row=this.db.prepare('SELECT status,current_concept,diagnostic_index FROM learner_sessions WHERE student_id=?').get(studentId) as {status:string;current_concept:string|null;diagnostic_index:number}|undefined; return row?{status:row.status,currentConcept:row.current_concept,diagnosticIndex:row.diagnostic_index}:undefined; }
  addEvidence(studentId:number,conceptId:string,kind:string,value:number|null,note:string):void { this.db.prepare('INSERT INTO evidence(student_id,concept_id,kind,value,note,created_at) VALUES(?,?,?,?,?,?)').run(studentId,conceptId,kind,value,note,new Date().toISOString()); }
  listEvidence(studentId:number,conceptId?:string):EvidenceRecord[] { const rows=(conceptId===undefined?this.db.prepare('SELECT id,student_id,concept_id,kind,value,note,created_at FROM evidence WHERE student_id=? ORDER BY id').all(studentId):this.db.prepare('SELECT id,student_id,concept_id,kind,value,note,created_at FROM evidence WHERE student_id=? AND concept_id=? ORDER BY id').all(studentId,conceptId)) as any[]; return rows.map(row=>({id:row.id,studentId:row.student_id,conceptId:row.concept_id,kind:row.kind,value:row.value===null?null:Number(row.value),note:row.note??'',createdAt:row.created_at})); }
  addMisconception(studentId:number,conceptId:string,code:string,note:string):MisconceptionRecord { const result=this.db.prepare('INSERT INTO misconceptions(student_id,concept_id,code,note,status,created_at) VALUES(?,?,?,?,?,?)').run(studentId,conceptId,code,note,'open',new Date().toISOString()); return this.getMisconception(Number(result.lastInsertRowid))!; }
  getMisconception(id:number):MisconceptionRecord|undefined { const row=this.db.prepare('SELECT id,student_id,concept_id,code,note,status,created_at,resolved_at FROM misconceptions WHERE id=?').get(id) as any; return row?{id:row.id,studentId:row.student_id,conceptId:row.concept_id,code:row.code,note:row.note,status:row.status,createdAt:row.created_at,resolvedAt:row.resolved_at}:undefined; }
  listOpenMisconceptions(studentId:number,conceptId?:string):MisconceptionRecord[] { const rows=(conceptId===undefined?this.db.prepare("SELECT id,student_id,concept_id,code,note,status,created_at,resolved_at FROM misconceptions WHERE student_id=? AND status='open' ORDER BY id").all(studentId):this.db.prepare("SELECT id,student_id,concept_id,code,note,status,created_at,resolved_at FROM misconceptions WHERE student_id=? AND concept_id=? AND status='open' ORDER BY id").all(studentId,conceptId)) as any[]; return rows.map(row=>({id:row.id,studentId:row.student_id,conceptId:row.concept_id,code:row.code,note:row.note,status:row.status,createdAt:row.created_at,resolvedAt:row.resolved_at})); }
  resolveMisconception(id:number):void { this.db.prepare("UPDATE misconceptions SET status='resolved',resolved_at=? WHERE id=? AND status='open'").run(new Date().toISOString(),id); }
  saveResume(studentId:number,lessonId:string,problemId:string|null,step:number):void { if(!lessonId.trim()||!Number.isInteger(step)||step<0)throw new Error('Invalid resume state'); this.db.prepare(`INSERT INTO resume_state(student_id,lesson_id,problem_id,step,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET lesson_id=excluded.lesson_id,problem_id=excluded.problem_id,step=excluded.step,updated_at=excluded.updated_at`).run(studentId,lessonId,problemId,step,new Date().toISOString()); }
  getResume(studentId:number):ResumeState|undefined { const row=this.db.prepare('SELECT lesson_id,problem_id,step,updated_at FROM resume_state WHERE student_id=?').get(studentId) as {lesson_id:string;problem_id:string|null;step:number;updated_at:string}|undefined; return row?{lessonId:row.lesson_id,problemId:row.problem_id,step:row.step,updatedAt:row.updated_at}:undefined; }
  scheduleReview(studentId:number,conceptId:string,correct:boolean):ReviewRecord { const current=this.db.prepare('SELECT interval_days,repetitions FROM reviews WHERE student_id=? AND concept_id=?').get(studentId,conceptId) as {interval_days:number;repetitions:number}|undefined; const repetitions=correct?(current?.repetitions??0)+1:0; const intervalDays=correct?Math.min(30,Math.max(1,(current?.interval_days??0)*2||1)):1; const dueAt=new Date(Date.now()+intervalDays*86400000).toISOString(); this.db.prepare(`INSERT INTO reviews(student_id,concept_id,due_at,interval_days,repetitions) VALUES(?,?,?,?,?) ON CONFLICT(student_id,concept_id) DO UPDATE SET due_at=excluded.due_at,interval_days=excluded.interval_days,repetitions=excluded.repetitions`).run(studentId,conceptId,dueAt,intervalDays,repetitions); return {conceptId,dueAt,intervalDays,repetitions}; }
  getDueReviews(studentId:number,now=new Date().toISOString()):ReviewRecord[] { const rows=this.db.prepare('SELECT concept_id,due_at,interval_days,repetitions FROM reviews WHERE student_id=? AND due_at<=? ORDER BY due_at').all(studentId,now) as Array<{concept_id:string;due_at:string;interval_days:number;repetitions:number}>; return rows.map(r=>({conceptId:r.concept_id,dueAt:r.due_at,intervalDays:r.interval_days,repetitions:r.repetitions})); }
  recordProblemAttempt(studentId:number,problemId:string,conceptId:string,answer:string,correct:boolean,reasoning:string,confidence:number|null,reasoningSignals:ReasoningSignal[]=[],misconceptionCodes:string[]=[]):ProblemAttemptRecord { if(!reasoning.trim())throw new Error('Reasoning is required for a problem attempt'); if(confidence!==null&&(!Number.isFinite(confidence)||confidence<0||confidence>100))throw new Error('Confidence must be between 0 and 100'); const createdAt=new Date().toISOString(); const result=this.db.prepare('INSERT INTO problem_attempts(student_id,problem_id,concept_id,answer,correct,reasoning,confidence,reasoning_signals,misconception_codes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(studentId,problemId,conceptId,answer,correct?1:0,reasoning,confidence,JSON.stringify(reasoningSignals),JSON.stringify(misconceptionCodes),createdAt); return {id:Number(result.lastInsertRowid),studentId,problemId,conceptId,answer,correct,reasoning,confidence,reasoningSignals,misconceptionCodes,createdAt}; }
  listProblemAttempts(studentId:number,problemId?:string):ProblemAttemptRecord[] { const rows=(problemId===undefined?this.db.prepare('SELECT id,student_id,problem_id,concept_id,answer,correct,reasoning,confidence,reasoning_signals,misconception_codes,created_at FROM problem_attempts WHERE student_id=? ORDER BY id').all(studentId):this.db.prepare('SELECT id,student_id,problem_id,concept_id,answer,correct,reasoning,confidence,reasoning_signals,misconception_codes,created_at FROM problem_attempts WHERE student_id=? AND problem_id=? ORDER BY id').all(studentId,problemId)) as any[]; return rows.map(row=>({id:row.id,studentId:row.student_id,problemId:row.problem_id,conceptId:row.concept_id,answer:row.answer,correct:Boolean(row.correct),reasoning:row.reasoning,confidence:row.confidence===null?null:Number(row.confidence),reasoningSignals:JSON.parse(row.reasoning_signals),misconceptionCodes:JSON.parse(row.misconception_codes),createdAt:row.created_at})); }
}