export function teacherDashboardHtml(): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vita — Classroom Intelligence</title><style>
  :root{font-family:Inter,system-ui,sans-serif;color:#17202a;background:#f6f7f9}body{margin:0}.shell{max-width:1180px;margin:auto;padding:32px 20px}.top{display:flex;gap:12px;align-items:end;justify-content:space-between;flex-wrap:wrap}.top h1{margin:0}.controls{display:flex;gap:8px;flex-wrap:wrap}input,button{font:inherit;padding:10px 12px;border:1px solid #cbd1d8;border-radius:8px;background:white}button{cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;margin:22px 0}.card{background:white;border:1px solid #e1e5e9;border-radius:12px;padding:18px}.metric{font-size:28px;font-weight:700}.muted{color:#68727d}.section{margin-top:26px}.rows{display:grid;gap:8px}.row{display:flex;justify-content:space-between;gap:16px;padding:12px;background:white;border:1px solid #e1e5e9;border-radius:9px}.pill{padding:3px 8px;border-radius:999px;background:#eef1f4}.error{padding:12px;background:#fff0f0;border:1px solid #e2aaaa;border-radius:8px}.empty{padding:20px;background:white;border:1px dashed #cbd1d8;border-radius:9px}.bar{height:8px;background:#e5e8eb;border-radius:9px;overflow:hidden}.bar i{display:block;height:100%;background:#5d6874}</style></head><body><main class="shell">
  <div class="top"><div><div class="muted">Vita Learning Intelligence</div><h1>Classroom</h1></div><div class="controls"><input id="staff" type="number" min="1" placeholder="Staff ID"><input id="classroom" type="number" min="1" placeholder="Classroom ID"><button id="load">Load intelligence</button></div></div>
  <div id="status" class="section muted">Enter your staff ID and an authorized classroom ID.</div><div id="app"></div>
</main><script>
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
async function load(){const staff=$('staff').value,id=$('classroom').value;if(!staff||!id){$('status').textContent='Staff ID and classroom ID are required.';return}$('status').textContent='Loading…';try{const r=await fetch('/v1/teacher/classroom?classroomId='+encodeURIComponent(id),{headers:{'x-vita-staff-id':staff}});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');render(data);$('status').textContent='Live classroom intelligence';}catch(e){$('status').innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
function render(d){const repaired=d.interventionEffectiveness.repaired,attempts=d.interventionEffectiveness.attempts;const rate=d.interventionEffectiveness.repairRate===null?'—':Math.round(d.interventionEffectiveness.repairRate*100)+'%';$('app').innerHTML=\`
<h2>\${esc(d.name)} <span class="pill">\${esc(d.code)}</span></h2><div class="grid"><div class="card"><div class="muted">Students</div><div class="metric">\${d.students}</div></div><div class="card"><div class="muted">Remediation repair rate</div><div class="metric">\${rate}</div><div class="muted">\${repaired} repaired / \${attempts} attempts</div></div><div class="card"><div class="muted">Need attention</div><div class="metric">\${d.attention.length}</div></div><div class="card"><div class="muted">Ready to advance</div><div class="metric">\${d.readyToAdvance.length}</div></div></div>
<section class="section"><h2>Class bottlenecks</h2><div class="rows">\${d.bottlenecks.length?d.bottlenecks.map(x=>'<div class="row"><span><strong>'+esc(x.conceptId)+'</strong><br><span class="muted">'+esc(x.reason)+'</span></span><span>'+x.affectedLearners+' learners<br>'+Math.round(x.averageMastery)+'% mastery</span></div>').join(''):'<div class="empty">No current prerequisite bottlenecks detected.</div>'}</div></section>
<section class="section"><h2>Misconception patterns</h2><div class="rows">\${d.misconceptions.length?d.misconceptions.map(x=>'<div class="row"><span><strong>'+esc(x.code)+'</strong><br><span class="muted">'+esc(x.conceptId)+'</span></span><span>'+x.affectedLearners+' learners · '+x.totalOccurrences+' occurrences<br>'+Math.round(x.averageConfidence)+'% confidence</span></div>').join(''):'<div class="empty">No active misconception pattern across the class.</div>'}</div></section>
<section class="section"><h2>Intervention strategies</h2><div class="rows">\${d.strategyEffectiveness.length?d.strategyEffectiveness.map(x=>'<div class="card"><strong>'+esc(x.strategy)+'</strong><div class="muted">'+x.repaired+' repaired / '+x.attempts+' attempts</div><div class="bar"><i style="width:'+Math.round((x.repairRate??0)*100)+'%"></i></div></div>').join(''):'<div class="empty">No remediation outcomes yet.</div>'}</div></section>
<section class="section"><h2>Who needs attention?</h2><div class="rows">\${d.attention.length?d.attention.map(x=>'<div class="row"><span><strong>Learner '+x.studentId+'</strong> <span class="pill">'+x.attention+'</span><br><span class="muted">'+x.reasons.map(esc).join(' · ')+'</span></span><span>'+x.activeMisconceptions+' active misconceptions<br>'+x.dueReviews+' reviews due</span></div>').join(''):'<div class="empty">No learner currently meets the attention thresholds.</div>'}</div></section>\`}
$('load').onclick=load;$('classroom').addEventListener('keydown',e=>{if(e.key==='Enter')load()});
</script></body></html>`;
}
