import { createServer } from 'node:http';
import { createPostgresPool } from './infrastructure/postgres.js';
import { PostgresLearningStore } from './infrastructure/postgres-store.js';
import { PostgresLearningEngine } from './application/postgres-learning-engine.js';
import { getPostgresLearnerTimeline } from './infrastructure/postgres-timeline.js';
import { getRemediationProblem } from './interventions.js';
import { getReviewProblemForConcept } from './reviews.js';
import { getConcept, validateCurriculum } from './curriculum.js';
import { getPracticeProblem, getPracticeProblemForConcept } from './practice.js';
import { evaluatePractice } from './practice-evaluator.js';
validateCurriculum();
const pool=createPostgresPool();const store=new PostgresLearningStore(pool);const engine=new PostgresLearningEngine(store);const port=Number(process.env.VITA_API_PORT??4310);const json=(status:number,body:unknown)=>({status,body:JSON.stringify(body)});
async function student(name:string|null){const nickname=name?.trim();if(!nickname)throw new Error('student is required');return store.ensureStudent(nickname);}
function readBody(req:import('node:http').IncomingMessage):Promise<Record<string,unknown>>{return new Promise((resolve,reject)=>{let raw='';req.setEncoding('utf8');req.on('data',chunk=>{raw+=chunk;if(raw.length>1_000_000)reject(new Error('request body too large'));});req.on('end',()=>{try{const value=raw?JSON.parse(raw):{};if(!value||typeof value!=='object'||Array.isArray(value))throw new Error();resolve(value as Record<string,unknown>);}catch{reject(new Error('invalid JSON'));}});req.on('error',reject);});}
async function route(req:import('node:http').IncomingMessage,res:import('node:http').ServerResponse){let result=json(500,{error:'request failed'});try{const url=new URL(req.url??'/',`http://${req.headers.host??'127.0.0.1'}`);
if(req.method==='GET'&&url.pathname==='/health'){await pool.query('SELECT 1');result=json(200,{status:'ok',service:'vita-adaptive-engine',database:'postgresql'});}
else if(req.method==='GET'&&url.pathname==='/v1/snapshot'){const id=await student(url.searchParams.get('student'));result=json(200,await engine.start(id));}
else if(req.method==='GET'&&url.pathname==='/v1/timeline'){const id=await student(url.searchParams.get('student'));result=json(200,{events:await getPostgresLearnerTimeline(store,id)});}
else if(req.method==='GET'&&url.pathname==='/v1/next'){const id=await student(url.searchParams.get('student'));const snapshot=await engine.start(id);const review=snapshot.dueReviews[0];if(review)result=json(200,{action:'review',review,problem:getReviewProblemForConcept(review.conceptId),snapshot});else{const intervention=await engine.nextIntervention(id);if(intervention)result=json(200,{action:'remediation',intervention,problem:getRemediationProblem(intervention.problemId),snapshot:await engine.snapshot(id)});else{const current=snapshot.currentConcept??snapshot.nextConcept??'forces';const problem=getPracticeProblemForConcept(current);result=json(200,{action:problem?'practice':'idle',problem:problem??null,snapshot});}}}
else if(req.method==='GET'&&url.pathname==='/v1/practice'){const id=await student(url.searchParams.get('student'));const snapshot=await engine.start(id);const requested=url.searchParams.get('problemId');const problem=requested?getPracticeProblem(requested):getPracticeProblemForConcept(snapshot.currentConcept??snapshot.nextConcept??'forces');result=json(200,{problem:problem??null,snapshot});}
else if(req.method==='POST'&&url.pathname==='/v1/practice'){const body=await readBody(req);const id=await student(typeof body.student==='string'?body.student:null);if(typeof body.problemId!=='string')throw new Error('problemId is required');const problem=getPracticeProblem(body.problemId);if(!problem)throw new Error('unknown practice problem');if(typeof body.reasoning!=='string'||typeof body.answer!=='string')throw new Error('reasoning and answer are required');const evaluation=evaluatePractice(problem,body.reasoning,body.answer);const snapshot=await engine.recordStructuredAttempt(id,problem.conceptId,{correct:evaluation.correct,reasoning:body.reasoning,problemId:problem.id,confidence:typeof body.confidence==='number'?body.confidence:null,hintUsed:body.hintUsed===true,durationSeconds:typeof body.durationSeconds==='number'?body.durationSeconds:null});result=json(200,{evaluation,snapshot});}
else if(req.method==='POST'&&url.pathname==='/v1/attempt'){const body=await readBody(req);const id=await student(typeof body.student==='string'?body.student:null);if(typeof body.conceptId!=='string')throw new Error('conceptId is required');getConcept(body.conceptId);if(typeof body.reasoning!=='string')throw new Error('reasoning is required');if(typeof body.correct!=='boolean')throw new Error('correct must be a boolean');result=json(200,await engine.recordStructuredAttempt(id,body.conceptId,{correct:body.correct,reasoning:body.reasoning,problemId:typeof body.problemId==='string'?body.problemId:null,confidence:typeof body.confidence==='number'?body.confidence:null,hintUsed:body.hintUsed===true,durationSeconds:typeof body.durationSeconds==='number'?body.durationSeconds:null,misconceptionCodes:Array.isArray(body.misconceptionCodes)?body.misconceptionCodes.filter((x):x is string=>typeof x==='string'):undefined,misconceptionSeverity:typeof body.misconceptionSeverity==='number'?body.misconceptionSeverity:undefined}));}
else if(req.method==='GET'&&url.pathname==='/v1/intervention'){const id=await student(url.searchParams.get('student'));const intervention=await engine.nextIntervention(id);result=json(200,intervention?{intervention,problem:getRemediationProblem(intervention.problemId),snapshot:await engine.snapshot(id)}:{intervention:null,snapshot:await engine.snapshot(id)});}
else if(req.method==='POST'&&url.pathname==='/v1/remediation'){const body=await readBody(req);const id=await student(typeof body.student==='string'?body.student:null);const interventionId=Number(body.interventionId);if(!Number.isInteger(interventionId))throw new Error('interventionId must be an integer');if(typeof body.reasoning!=='string'||typeof body.answer!=='string')throw new Error('reasoning and answer are required');result=json(200,await engine.submitRemediationAttempt(id,interventionId,{reasoning:body.reasoning,answer:body.answer,confidence:typeof body.confidence==='number'?body.confidence:null,hintUsed:body.hintUsed===true,durationSeconds:typeof body.durationSeconds==='number'?body.durationSeconds:null}));}
else if(req.method==='GET'&&url.pathname==='/v1/review'){const id=await student(url.searchParams.get('student'));const review=await engine.nextReview(id);const problem=review?getReviewProblemForConcept(review.conceptId):undefined;result=json(200,{review:review??null,problem:problem??null,snapshot:await engine.snapshot(id)});}
else if(req.method==='POST'&&url.pathname==='/v1/review'){const body=await readBody(req);const id=await student(typeof body.student==='string'?body.student:null);if(typeof body.reasoning!=='string'||typeof body.answer!=='string')throw new Error('reasoning and answer are required');result=json(200,await engine.submitReviewAttempt(id,{reasoning:body.reasoning,answer:body.answer,confidence:typeof body.confidence==='number'?body.confidence:null,hintUsed:body.hintUsed===true,durationSeconds:typeof body.durationSeconds==='number'?body.durationSeconds:null}));}
else result=json(404,{error:'not_found'});}catch(error){result=json(error instanceof Error&&error.message.startsWith('unknown')?404:400,{error:error instanceof Error?error.message:'request failed'});}res.writeHead(result.status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(result.body);}
const server=createServer((req,res)=>{void route(req,res);});server.listen(port,'127.0.0.1',()=>console.log(`Vita adaptive API listening on 127.0.0.1:${port}`));const shutdown=()=>{server.close(()=>{void store.close();});};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
